// Generated by `npm run catalog:generate`.
// Do not edit manually. Edit catalog-overrides.ts, then regenerate.
import type { ParameterCatalog } from "./catalog-overrides";

export const terraformAwsParameterCatalog = {
  "provider": "aws",
  "generatedAt": "2026-06-24T00:00:00.000Z",
  "source": "terraform-provider-aws-schema@6.51.0",
  "resources": {
    "aws_vpc": [
      {
        "name": "cidrBlock",
        "terraformName": "cidr_block",
        "label": "CIDR block",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "VPC가 사용할 IPv4 네트워크 범위입니다.",
        "inputKind": "text",
        "placeholder": "10.0.0.0/16"
      },
      {
        "name": "instanceTenancy",
        "terraformName": "instance_tenancy",
        "label": "Instance tenancy",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "EC2 인스턴스의 기본 테넌시입니다. 학습용은 default가 안전합니다.",
        "inputKind": "select",
        "options": [
          "default",
          "dedicated",
          "host"
        ]
      },
      {
        "name": "enableDnsSupport",
        "terraformName": "enable_dns_support",
        "label": "DNS support",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "VPC 안에서 AWS DNS 확인을 사용할지 정합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "enableDnsHostnames",
        "terraformName": "enable_dns_hostnames",
        "label": "DNS hostnames",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "VPC 안의 인스턴스에 DNS hostname을 부여할지 정합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_subnet": [
      {
        "name": "vpcId",
        "terraformName": "vpc_id",
        "label": "VPC",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Subnet이 속할 VPC입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_vpc"
        ]
      },
      {
        "name": "cidrBlock",
        "terraformName": "cidr_block",
        "label": "CIDR block",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "Subnet이 사용할 IPv4 네트워크 범위입니다. VPC CIDR 안에 있어야 합니다.",
        "inputKind": "text",
        "placeholder": "10.0.1.0/24"
      },
      {
        "name": "availabilityZone",
        "terraformName": "availability_zone",
        "label": "Availability zone",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Subnet을 둘 가용 영역입니다.",
        "inputKind": "text",
        "placeholder": "ap-northeast-2a"
      },
      {
        "name": "mapPublicIpOnLaunch",
        "terraformName": "map_public_ip_on_launch",
        "label": "Auto-assign public IPv4",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "이 Subnet에서 시작하는 인스턴스에 public IPv4를 자동 할당할지 정합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_internet_gateway": [
      {
        "name": "vpcId",
        "terraformName": "vpc_id",
        "label": "VPC",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "Internet Gateway를 연결할 VPC입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_vpc"
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_route_table": [
      {
        "name": "vpcId",
        "terraformName": "vpc_id",
        "label": "VPC",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Route Table이 속할 VPC입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_vpc"
        ]
      },
      {
        "name": "route",
        "terraformName": "route",
        "label": "Routes",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "대표 라우팅 규칙입니다. IGW 또는 NAT Gateway를 대상으로 연결합니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "cidrBlock",
            "terraformName": "cidr_block",
            "label": "Destination CIDR",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": true,
            "sensitive": false,
            "description": "라우팅 대상 CIDR입니다.",
            "inputKind": "text",
            "placeholder": "0.0.0.0/0"
          },
          {
            "name": "gatewayId",
            "terraformName": "gateway_id",
            "label": "Internet Gateway",
            "type": "string",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "인터넷으로 나가는 라우트에 사용할 Internet Gateway입니다.",
            "inputKind": "reference-picker",
            "referenceTargetTypes": [
              "aws_internet_gateway"
            ]
          },
          {
            "name": "natGatewayId",
            "terraformName": "nat_gateway_id",
            "label": "NAT Gateway",
            "type": "string",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "프라이빗 Subnet의 outbound 라우트에 사용할 NAT Gateway입니다.",
            "inputKind": "reference-picker",
            "referenceTargetTypes": [
              "aws_nat_gateway"
            ]
          }
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_nat_gateway": [
      {
        "name": "subnetId",
        "terraformName": "subnet_id",
        "label": "Subnet",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "NAT Gateway를 배치할 public Subnet입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_subnet"
        ]
      },
      {
        "name": "allocationId",
        "terraformName": "allocation_id",
        "label": "Elastic IP allocation",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "NAT Gateway에 연결할 Elastic IP allocation입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_eip"
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_vpc_endpoint": [
      {
        "name": "vpcId",
        "terraformName": "vpc_id",
        "label": "VPC",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "VPC Endpoint를 둘 VPC입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_vpc"
        ]
      },
      {
        "name": "serviceName",
        "terraformName": "service_name",
        "label": "Service name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "연결할 AWS 서비스 endpoint 이름입니다.",
        "inputKind": "text",
        "placeholder": "com.amazonaws.ap-northeast-2.s3"
      },
      {
        "name": "vpcEndpointType",
        "terraformName": "vpc_endpoint_type",
        "label": "Endpoint type",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Gateway 또는 Interface endpoint 중 하나를 선택합니다.",
        "inputKind": "select",
        "options": [
          "Gateway",
          "Interface"
        ]
      },
      {
        "name": "subnetIds",
        "terraformName": "subnet_ids",
        "label": "Subnets",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Interface endpoint를 배치할 Subnet 목록입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_subnet"
        ]
      },
      {
        "name": "routeTableIds",
        "terraformName": "route_table_ids",
        "label": "Route tables",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Gateway endpoint에 연결할 Route Table 목록입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_route_table"
        ]
      },
      {
        "name": "securityGroupIds",
        "terraformName": "security_group_ids",
        "label": "Security groups",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Interface endpoint에 연결할 Security Group 목록입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_security_group"
        ]
      },
      {
        "name": "privateDnsEnabled",
        "terraformName": "private_dns_enabled",
        "label": "Private DNS",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Interface endpoint에서 private DNS를 사용할지 정합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_security_group": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "AWS에 표시될 보안 그룹 이름입니다.",
        "inputKind": "text",
        "placeholder": "web-sg"
      },
      {
        "name": "description",
        "terraformName": "description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "보안 그룹의 목적입니다.",
        "inputKind": "text",
        "placeholder": "Allow web traffic"
      },
      {
        "name": "vpcId",
        "terraformName": "vpc_id",
        "label": "VPC",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "보안 그룹을 둘 VPC입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_vpc"
        ]
      },
      {
        "name": "ingress",
        "terraformName": "ingress",
        "label": "Ingress rules",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "리소스로 들어오는 트래픽 규칙입니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "description",
            "terraformName": "description",
            "label": "Description",
            "type": "string",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "규칙의 목적을 짧게 적습니다.",
            "inputKind": "text",
            "placeholder": "Allow HTTPS"
          },
          {
            "name": "fromPort",
            "terraformName": "from_port",
            "label": "From port",
            "type": "number",
            "required": true,
            "optional": false,
            "computed": true,
            "sensitive": false,
            "description": "허용할 시작 포트입니다. 모든 포트를 뜻할 때는 0을 사용합니다.",
            "inputKind": "number",
            "placeholder": "443"
          },
          {
            "name": "toPort",
            "terraformName": "to_port",
            "label": "To port",
            "type": "number",
            "required": true,
            "optional": false,
            "computed": true,
            "sensitive": false,
            "description": "허용할 끝 포트입니다. 단일 포트 규칙에서는 From port와 같은 값을 사용합니다.",
            "inputKind": "number",
            "placeholder": "443"
          },
          {
            "name": "protocol",
            "terraformName": "protocol",
            "label": "Protocol",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": true,
            "sensitive": false,
            "description": "tcp, udp, icmp 또는 모든 프로토콜을 뜻하는 -1을 선택합니다.",
            "inputKind": "select",
            "options": [
              "tcp",
              "udp",
              "icmp",
              "-1"
            ]
          },
          {
            "name": "cidrBlocks",
            "terraformName": "cidr_blocks",
            "label": "CIDR blocks",
            "type": "list",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "허용하거나 라우팅할 IPv4 CIDR 목록입니다.",
            "inputKind": "text",
            "placeholder": "0.0.0.0/0"
          }
        ]
      },
      {
        "name": "egress",
        "terraformName": "egress",
        "label": "Egress rules",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "리소스에서 나가는 트래픽 규칙입니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "description",
            "terraformName": "description",
            "label": "Description",
            "type": "string",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "규칙의 목적을 짧게 적습니다.",
            "inputKind": "text",
            "placeholder": "Allow HTTPS"
          },
          {
            "name": "fromPort",
            "terraformName": "from_port",
            "label": "From port",
            "type": "number",
            "required": true,
            "optional": false,
            "computed": true,
            "sensitive": false,
            "description": "허용할 시작 포트입니다. 모든 포트를 뜻할 때는 0을 사용합니다.",
            "inputKind": "number",
            "placeholder": "443"
          },
          {
            "name": "toPort",
            "terraformName": "to_port",
            "label": "To port",
            "type": "number",
            "required": true,
            "optional": false,
            "computed": true,
            "sensitive": false,
            "description": "허용할 끝 포트입니다. 단일 포트 규칙에서는 From port와 같은 값을 사용합니다.",
            "inputKind": "number",
            "placeholder": "443"
          },
          {
            "name": "protocol",
            "terraformName": "protocol",
            "label": "Protocol",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": true,
            "sensitive": false,
            "description": "tcp, udp, icmp 또는 모든 프로토콜을 뜻하는 -1을 선택합니다.",
            "inputKind": "select",
            "options": [
              "tcp",
              "udp",
              "icmp",
              "-1"
            ]
          },
          {
            "name": "cidrBlocks",
            "terraformName": "cidr_blocks",
            "label": "CIDR blocks",
            "type": "list",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "허용하거나 라우팅할 IPv4 CIDR 목록입니다.",
            "inputKind": "text",
            "placeholder": "0.0.0.0/0"
          }
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_security_group_rule": [
      {
        "name": "type",
        "terraformName": "type",
        "label": "Rule type",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "ingress 또는 egress 규칙을 선택합니다.",
        "inputKind": "select",
        "options": [
          "ingress",
          "egress"
        ]
      },
      {
        "name": "securityGroupId",
        "terraformName": "security_group_id",
        "label": "Security group",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "규칙을 붙일 Security Group입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_security_group"
        ]
      },
      {
        "name": "description",
        "terraformName": "description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "규칙의 목적을 짧게 적습니다.",
        "inputKind": "text",
        "placeholder": "Allow HTTPS"
      },
      {
        "name": "fromPort",
        "terraformName": "from_port",
        "label": "From port",
        "type": "number",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "허용할 시작 포트입니다. 모든 포트를 뜻할 때는 0을 사용합니다.",
        "inputKind": "number",
        "placeholder": "443"
      },
      {
        "name": "toPort",
        "terraformName": "to_port",
        "label": "To port",
        "type": "number",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "허용할 끝 포트입니다. 단일 포트 규칙에서는 From port와 같은 값을 사용합니다.",
        "inputKind": "number",
        "placeholder": "443"
      },
      {
        "name": "protocol",
        "terraformName": "protocol",
        "label": "Protocol",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "tcp, udp, icmp 또는 모든 프로토콜을 뜻하는 -1을 선택합니다.",
        "inputKind": "select",
        "options": [
          "tcp",
          "udp",
          "icmp",
          "-1"
        ]
      },
      {
        "name": "cidrBlocks",
        "terraformName": "cidr_blocks",
        "label": "CIDR blocks",
        "type": "list",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "허용하거나 라우팅할 IPv4 CIDR 목록입니다.",
        "inputKind": "text",
        "placeholder": "0.0.0.0/0"
      },
      {
        "name": "sourceSecurityGroupId",
        "terraformName": "source_security_group_id",
        "label": "Source security group",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "CIDR 대신 다른 Security Group을 source로 사용할 때 선택합니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_security_group"
        ]
      }
    ],
    "aws_iam_role": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "IAM Role 이름입니다.",
        "inputKind": "text",
        "placeholder": "lambda-exec-role"
      },
      {
        "name": "assumeRolePolicy",
        "terraformName": "assume_role_policy",
        "label": "Assume role policy",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "신뢰 정책 JSON입니다. MVP에서는 text로 입력하고 실제 secret은 넣지 않습니다.",
        "inputKind": "text",
        "placeholder": "placeholder:assume_role_policy_json"
      },
      {
        "name": "description",
        "terraformName": "description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "역할의 목적입니다.",
        "inputKind": "text",
        "placeholder": "Execution role for practice Lambda"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_iam_policy": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "IAM Policy 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-readonly-policy"
      },
      {
        "name": "policy",
        "terraformName": "policy",
        "label": "Policy JSON",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "정책 문서 JSON입니다. MVP에서는 text로 입력합니다.",
        "inputKind": "text",
        "placeholder": "placeholder:iam_policy_json"
      },
      {
        "name": "description",
        "terraformName": "description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "정책의 목적입니다.",
        "inputKind": "text",
        "placeholder": "Least-privilege practice policy"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_iam_instance_profile": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "EC2에 연결할 Instance Profile 이름입니다.",
        "inputKind": "text",
        "placeholder": "ec2-practice-profile"
      },
      {
        "name": "role",
        "terraformName": "role",
        "label": "IAM role",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Instance Profile에 넣을 IAM Role입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_iam_role"
        ],
        "referenceAttribute": "name"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_kms_key": [
      {
        "name": "description",
        "terraformName": "description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "KMS Key의 용도입니다.",
        "inputKind": "text",
        "placeholder": "Practice encryption key"
      },
      {
        "name": "enableKeyRotation",
        "terraformName": "enable_key_rotation",
        "label": "Key rotation",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "연 단위 자동 key rotation을 사용할지 정합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "deletionWindowInDays",
        "terraformName": "deletion_window_in_days",
        "label": "Deletion window",
        "type": "number",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "삭제 예약 후 실제 삭제까지 기다리는 일수입니다.",
        "inputKind": "number",
        "placeholder": "7"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_instance": [
      {
        "name": "ami",
        "terraformName": "ami",
        "label": "AMI",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "EC2 인스턴스에 사용할 AMI data source입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_ami"
        ]
      },
      {
        "name": "instanceType",
        "terraformName": "instance_type",
        "label": "Instance type",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "인스턴스 크기입니다. 학습용은 작은 타입을 우선 사용합니다.",
        "inputKind": "select",
        "options": [
          "t3.micro",
          "t3.small",
          "t4g.micro",
          "t4g.small"
        ]
      },
      {
        "name": "subnetId",
        "terraformName": "subnet_id",
        "label": "Subnet",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "EC2 인스턴스를 배치할 Subnet입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_subnet"
        ]
      },
      {
        "name": "vpcSecurityGroupIds",
        "terraformName": "vpc_security_group_ids",
        "label": "Security groups",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "인스턴스에 연결할 VPC 보안 그룹 목록입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_security_group"
        ]
      },
      {
        "name": "keyName",
        "terraformName": "key_name",
        "label": "Key pair",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "SSH 접속에 사용할 Key Pair입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_key_pair"
        ],
        "referenceAttribute": "key_name"
      },
      {
        "name": "iamInstanceProfile",
        "terraformName": "iam_instance_profile",
        "label": "Instance profile",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "EC2에 연결할 IAM Instance Profile입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_iam_instance_profile"
        ],
        "referenceAttribute": "name"
      },
      {
        "name": "associatePublicIpAddress",
        "terraformName": "associate_public_ip_address",
        "label": "Public IP",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "인스턴스에 public IPv4를 직접 연결할지 정합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "userData",
        "terraformName": "user_data",
        "label": "User data",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": true,
        "description": "부팅 스크립트는 secret을 포함할 수 있어 실제 값 대신 var.user_data 같은 변수 참조만 저장합니다.",
        "inputKind": "text",
        "placeholder": "var.ec2_user_data"
      },
      {
        "name": "rootBlockDevice",
        "terraformName": "root_block_device",
        "label": "Root block device",
        "type": "list",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "루트 EBS 볼륨의 기본 설정입니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "volumeSize",
            "terraformName": "volume_size",
            "label": "Volume size",
            "type": "number",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "루트 볼륨 크기입니다. 단위는 GiB입니다.",
            "inputKind": "number",
            "placeholder": "8"
          },
          {
            "name": "volumeType",
            "terraformName": "volume_type",
            "label": "Volume type",
            "type": "string",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "루트 볼륨 유형입니다.",
            "inputKind": "select",
            "options": [
              "gp3",
              "gp2",
              "io2"
            ]
          },
          {
            "name": "encrypted",
            "terraformName": "encrypted",
            "label": "Encrypted",
            "type": "boolean",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "루트 볼륨 암호화 여부입니다.",
            "inputKind": "checkbox"
          }
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_ami": [
      {
        "name": "owners",
        "terraformName": "owners",
        "label": "Owners",
        "type": "list",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "AMI owner 목록입니다. Amazon Linux는 amazon을 사용할 수 있습니다.",
        "inputKind": "text",
        "placeholder": "amazon"
      },
      {
        "name": "mostRecent",
        "terraformName": "most_recent",
        "label": "Most recent",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "조건에 맞는 최신 AMI를 선택할지 정합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "filterName",
        "terraformName": "filter.name",
        "label": "Filter name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "AMI 조회 filter 이름입니다.",
        "inputKind": "text",
        "placeholder": "name"
      },
      {
        "name": "filterValues",
        "terraformName": "filter.values",
        "label": "Filter values",
        "type": "set",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "AMI 조회 filter 값 목록입니다.",
        "inputKind": "text",
        "placeholder": "amzn2-ami-hvm-*-x86_64-gp2"
      }
    ],
    "aws_key_pair": [
      {
        "name": "keyName",
        "terraformName": "key_name",
        "label": "Key name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "AWS에 등록될 Key Pair 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-key"
      },
      {
        "name": "publicKey",
        "terraformName": "public_key",
        "label": "Public key",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "등록할 public key입니다. private key는 절대 입력하지 않습니다.",
        "inputKind": "text",
        "placeholder": "var.public_key"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_eip": [
      {
        "name": "domain",
        "terraformName": "domain",
        "label": "Domain",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "VPC용 Elastic IP는 vpc를 선택합니다.",
        "inputKind": "select",
        "options": [
          "vpc"
        ]
      },
      {
        "name": "instance",
        "terraformName": "instance",
        "label": "EC2 instance",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Elastic IP를 직접 연결할 EC2 인스턴스입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_instance"
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_launch_template": [
      {
        "name": "namePrefix",
        "terraformName": "name_prefix",
        "label": "Name prefix",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Launch Template 이름 prefix입니다.",
        "inputKind": "text",
        "placeholder": "practice-web-"
      },
      {
        "name": "imageId",
        "terraformName": "image_id",
        "label": "AMI",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Launch Template에 사용할 AMI data source입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_ami"
        ]
      },
      {
        "name": "instanceType",
        "terraformName": "instance_type",
        "label": "Instance type",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Auto Scaling에서 사용할 EC2 인스턴스 타입입니다.",
        "inputKind": "select",
        "options": [
          "t3.micro",
          "t3.small",
          "t4g.micro",
          "t4g.small"
        ]
      },
      {
        "name": "keyName",
        "terraformName": "key_name",
        "label": "Key pair",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "인스턴스 접속에 사용할 Key Pair입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_key_pair"
        ],
        "referenceAttribute": "key_name"
      },
      {
        "name": "vpcSecurityGroupIds",
        "terraformName": "vpc_security_group_ids",
        "label": "Security groups",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Launch Template 인스턴스에 연결할 Security Group 목록입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_security_group"
        ]
      },
      {
        "name": "userData",
        "terraformName": "user_data",
        "label": "User data",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": true,
        "description": "부팅 스크립트는 실제 값 대신 변수 참조나 placeholder만 저장합니다.",
        "inputKind": "text",
        "placeholder": "var.launch_template_user_data"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_autoscaling_group": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Auto Scaling Group 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-web-asg"
      },
      {
        "name": "minSize",
        "terraformName": "min_size",
        "label": "Min size",
        "type": "number",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "최소 인스턴스 수입니다.",
        "inputKind": "number",
        "placeholder": "1"
      },
      {
        "name": "maxSize",
        "terraformName": "max_size",
        "label": "Max size",
        "type": "number",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "최대 인스턴스 수입니다.",
        "inputKind": "number",
        "placeholder": "2"
      },
      {
        "name": "desiredCapacity",
        "terraformName": "desired_capacity",
        "label": "Desired capacity",
        "type": "number",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "원하는 인스턴스 수입니다.",
        "inputKind": "number",
        "placeholder": "1"
      },
      {
        "name": "vpcZoneIdentifier",
        "terraformName": "vpc_zone_identifier",
        "label": "Subnets",
        "type": "set",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "Auto Scaling Group이 인스턴스를 배치할 Subnet 목록입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_subnet"
        ]
      },
      {
        "name": "launchTemplate",
        "terraformName": "launch_template",
        "label": "Launch template",
        "type": "list",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Auto Scaling Group에 연결할 Launch Template입니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "id",
            "terraformName": "id",
            "label": "Launch template",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": true,
            "sensitive": false,
            "description": "사용할 Launch Template입니다.",
            "inputKind": "reference-picker",
            "referenceTargetTypes": [
              "aws_launch_template"
            ]
          },
          {
            "name": "version",
            "terraformName": "version",
            "label": "Version",
            "type": "string",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "Launch Template version입니다.",
            "inputKind": "text",
            "placeholder": "$Latest"
          }
        ]
      },
      {
        "name": "tag",
        "terraformName": "tag",
        "label": "Tags",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Auto Scaling Group 태그입니다. 인스턴스 전파 여부를 함께 정합니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "key",
            "terraformName": "key",
            "label": "Key",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "태그 key입니다.",
            "inputKind": "text",
            "placeholder": "Name"
          },
          {
            "name": "value",
            "terraformName": "value",
            "label": "Value",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "태그 value입니다.",
            "inputKind": "text",
            "placeholder": "practice-web"
          },
          {
            "name": "propagateAtLaunch",
            "terraformName": "propagate_at_launch",
            "label": "Propagate at launch",
            "type": "boolean",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "새로 생성되는 EC2 인스턴스에 태그를 전파할지 정합니다.",
            "inputKind": "checkbox"
          }
        ]
      }
    ],
    "aws_s3_bucket": [
      {
        "name": "bucket",
        "terraformName": "bucket",
        "label": "Bucket name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "전역으로 고유해야 하는 S3 bucket 이름입니다. 비워두면 Terraform/AWS가 이름을 정하게 할 수 있습니다.",
        "inputKind": "text",
        "placeholder": "sketchcatch-practice-bucket"
      },
      {
        "name": "forceDestroy",
        "terraformName": "force_destroy",
        "label": "Force destroy",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "삭제 시 객체가 있어도 bucket을 제거할지 정합니다. 학습용에서는 비용 정리를 위해 의미를 꼭 확인해야 합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_s3_bucket_public_access_block": [
      {
        "name": "bucket",
        "terraformName": "bucket",
        "label": "Bucket",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Public Access Block을 적용할 S3 Bucket입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_s3_bucket"
        ]
      },
      {
        "name": "blockPublicAcls",
        "terraformName": "block_public_acls",
        "label": "Block public ACLs",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "퍼블릭 ACL 설정을 차단합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "blockPublicPolicy",
        "terraformName": "block_public_policy",
        "label": "Block public policy",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "퍼블릭 bucket policy를 차단합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "ignorePublicAcls",
        "terraformName": "ignore_public_acls",
        "label": "Ignore public ACLs",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "기존 퍼블릭 ACL을 무시합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "restrictPublicBuckets",
        "terraformName": "restrict_public_buckets",
        "label": "Restrict public buckets",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "퍼블릭 policy가 있는 bucket의 접근을 제한합니다.",
        "inputKind": "checkbox"
      }
    ],
    "aws_s3_bucket_versioning": [
      {
        "name": "bucket",
        "terraformName": "bucket",
        "label": "Bucket",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Versioning을 설정할 S3 Bucket입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_s3_bucket"
        ]
      },
      {
        "name": "status",
        "terraformName": "versioning_configuration.status",
        "label": "Versioning status",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Bucket versioning 상태입니다.",
        "inputKind": "select",
        "options": [
          "Enabled",
          "Suspended"
        ]
      }
    ],
    "aws_s3_bucket_server_side_encryption_configuration": [
      {
        "name": "bucket",
        "terraformName": "bucket",
        "label": "Bucket",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "기본 서버 측 암호화를 설정할 S3 Bucket입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_s3_bucket"
        ]
      },
      {
        "name": "sseAlgorithm",
        "terraformName": "rule.apply_server_side_encryption_by_default.sse_algorithm",
        "label": "SSE algorithm",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "기본 암호화 알고리즘입니다.",
        "inputKind": "select",
        "options": [
          "AES256",
          "aws:kms"
        ]
      },
      {
        "name": "kmsMasterKeyId",
        "terraformName": "rule.apply_server_side_encryption_by_default.kms_master_key_id",
        "label": "KMS key",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "aws:kms 사용 시 연결할 KMS Key입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_kms_key"
        ],
        "referenceAttribute": "arn"
      }
    ],
    "aws_s3_bucket_lifecycle_configuration": [
      {
        "name": "bucket",
        "terraformName": "bucket",
        "label": "Bucket",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Lifecycle rule을 적용할 S3 Bucket입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_s3_bucket"
        ]
      },
      {
        "name": "rule",
        "terraformName": "rule",
        "label": "Lifecycle rules",
        "type": "list",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "객체 보관/만료 정책의 핵심 rule입니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "id",
            "terraformName": "id",
            "label": "Rule ID",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "Lifecycle rule 식별자입니다.",
            "inputKind": "text",
            "placeholder": "expire-old-objects"
          },
          {
            "name": "status",
            "terraformName": "status",
            "label": "Status",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "Lifecycle rule 활성 상태입니다.",
            "inputKind": "select",
            "options": [
              "Enabled",
              "Disabled"
            ]
          },
          {
            "name": "expirationDays",
            "terraformName": "expiration.days",
            "label": "Expiration days",
            "type": "number",
            "required": false,
            "optional": true,
            "computed": true,
            "sensitive": false,
            "description": "객체를 만료 처리할 일수입니다.",
            "inputKind": "number",
            "placeholder": "30"
          }
        ]
      }
    ],
    "aws_ebs_volume": [
      {
        "name": "availabilityZone",
        "terraformName": "availability_zone",
        "label": "Availability zone",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "EBS Volume을 생성할 가용 영역입니다.",
        "inputKind": "text",
        "placeholder": "ap-northeast-2a"
      },
      {
        "name": "size",
        "terraformName": "size",
        "label": "Size",
        "type": "number",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "볼륨 크기입니다. 단위는 GiB입니다.",
        "inputKind": "number",
        "placeholder": "8"
      },
      {
        "name": "type",
        "terraformName": "type",
        "label": "Volume type",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "EBS 볼륨 유형입니다.",
        "inputKind": "select",
        "options": [
          "gp3",
          "gp2",
          "io2"
        ]
      },
      {
        "name": "encrypted",
        "terraformName": "encrypted",
        "label": "Encrypted",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "볼륨 암호화 여부입니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "kmsKeyId",
        "terraformName": "kms_key_id",
        "label": "KMS key",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "암호화에 사용할 KMS Key입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_kms_key"
        ],
        "referenceAttribute": "arn"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_db_instance": [
      {
        "name": "identifier",
        "terraformName": "identifier",
        "label": "Identifier",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "RDS 인스턴스 식별자입니다.",
        "inputKind": "text",
        "placeholder": "practice-db"
      },
      {
        "name": "allocatedStorage",
        "terraformName": "allocated_storage",
        "label": "Allocated storage",
        "type": "number",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "DB에 할당할 스토리지 크기입니다. 단위는 GiB입니다.",
        "inputKind": "number",
        "placeholder": "20"
      },
      {
        "name": "engine",
        "terraformName": "engine",
        "label": "Engine",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "사용할 RDS 데이터베이스 엔진입니다.",
        "inputKind": "select",
        "options": [
          "postgres",
          "mysql",
          "mariadb"
        ]
      },
      {
        "name": "instanceClass",
        "terraformName": "instance_class",
        "label": "Instance class",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "RDS 인스턴스 크기입니다. 학습용은 작은 클래스부터 선택합니다.",
        "inputKind": "select",
        "options": [
          "db.t3.micro",
          "db.t4g.micro",
          "db.t3.small"
        ]
      },
      {
        "name": "dbSubnetGroupName",
        "terraformName": "db_subnet_group_name",
        "label": "DB subnet group",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "RDS를 배치할 DB Subnet Group입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_db_subnet_group"
        ],
        "referenceAttribute": "name"
      },
      {
        "name": "username",
        "terraformName": "username",
        "label": "Username",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "마스터 사용자 이름입니다. 비밀번호는 별도 민감 필드로 다룹니다.",
        "inputKind": "text",
        "placeholder": "admin"
      },
      {
        "name": "password",
        "terraformName": "password",
        "label": "Password variable",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": true,
        "description": "실제 DB 비밀번호를 저장하지 않고 var.db_password 같은 Terraform 변수 참조만 저장합니다.",
        "inputKind": "text",
        "placeholder": "var.db_password"
      },
      {
        "name": "dbName",
        "terraformName": "db_name",
        "label": "DB name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "처음 만들 데이터베이스 이름입니다.",
        "inputKind": "text",
        "placeholder": "appdb"
      },
      {
        "name": "vpcSecurityGroupIds",
        "terraformName": "vpc_security_group_ids",
        "label": "Security groups",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "RDS에 연결할 VPC 보안 그룹 목록입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_security_group"
        ]
      },
      {
        "name": "publiclyAccessible",
        "terraformName": "publicly_accessible",
        "label": "Publicly accessible",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "DB를 인터넷에서 접근 가능하게 할지 정합니다. 학습용에서는 보통 끄는 편이 안전합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "skipFinalSnapshot",
        "terraformName": "skip_final_snapshot",
        "label": "Skip final snapshot",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "삭제 시 최종 스냅샷 생성을 건너뛸지 정합니다. 연습 환경 정리 정책과 함께 검토합니다.",
        "inputKind": "checkbox"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_db_subnet_group": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "DB Subnet Group 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-db-subnets"
      },
      {
        "name": "subnetIds",
        "terraformName": "subnet_ids",
        "label": "Subnets",
        "type": "set",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "RDS가 사용할 Subnet 목록입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_subnet"
        ]
      },
      {
        "name": "description",
        "terraformName": "description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Subnet Group의 목적입니다.",
        "inputKind": "text",
        "placeholder": "Private subnets for practice RDS"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_db_parameter_group": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "RDS Parameter Group 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-postgres-params"
      },
      {
        "name": "family",
        "terraformName": "family",
        "label": "Family",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "DB 엔진 major version family입니다.",
        "inputKind": "text",
        "placeholder": "postgres16"
      },
      {
        "name": "parameter",
        "terraformName": "parameter",
        "label": "Parameters",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "대표 DB 파라미터 override입니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "name",
            "terraformName": "name",
            "label": "Name",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "DB parameter 이름입니다.",
            "inputKind": "text",
            "placeholder": "log_min_duration_statement"
          },
          {
            "name": "value",
            "terraformName": "value",
            "label": "Value",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "DB parameter 값입니다.",
            "inputKind": "text",
            "placeholder": "1000"
          },
          {
            "name": "applyMethod",
            "terraformName": "apply_method",
            "label": "Apply method",
            "type": "string",
            "required": false,
            "optional": true,
            "computed": false,
            "sensitive": false,
            "description": "파라미터 적용 방식입니다.",
            "inputKind": "select",
            "options": [
              "immediate",
              "pending-reboot"
            ]
          }
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_db_option_group": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "RDS Option Group 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-mysql-options"
      },
      {
        "name": "engineName",
        "terraformName": "engine_name",
        "label": "Engine name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Option Group이 적용될 엔진입니다.",
        "inputKind": "select",
        "options": [
          "mysql",
          "mariadb",
          "oracle-ee",
          "sqlserver-ex"
        ]
      },
      {
        "name": "majorEngineVersion",
        "terraformName": "major_engine_version",
        "label": "Major engine version",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "엔진 major version입니다.",
        "inputKind": "text",
        "placeholder": "8.0"
      },
      {
        "name": "optionGroupDescription",
        "terraformName": "option_group_description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Option Group 설명입니다.",
        "inputKind": "text",
        "placeholder": "Practice DB option group"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_db_snapshot": [
      {
        "name": "dbInstanceIdentifier",
        "terraformName": "db_instance_identifier",
        "label": "DB instance",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "스냅샷을 만들 RDS Instance입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_db_instance"
        ],
        "referenceAttribute": "identifier"
      },
      {
        "name": "dbSnapshotIdentifier",
        "terraformName": "db_snapshot_identifier",
        "label": "Snapshot identifier",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "RDS Snapshot 식별자입니다.",
        "inputKind": "text",
        "placeholder": "practice-db-snapshot"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_dynamodb_table": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "DynamoDB Table 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-table"
      },
      {
        "name": "billingMode",
        "terraformName": "billing_mode",
        "label": "Billing mode",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "요금/처리량 모드입니다. 학습용은 PAY_PER_REQUEST가 단순합니다.",
        "inputKind": "select",
        "options": [
          "PAY_PER_REQUEST",
          "PROVISIONED"
        ]
      },
      {
        "name": "hashKey",
        "terraformName": "hash_key",
        "label": "Hash key",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": true,
        "sensitive": false,
        "description": "Partition key 이름입니다.",
        "inputKind": "text",
        "placeholder": "id"
      },
      {
        "name": "rangeKey",
        "terraformName": "range_key",
        "label": "Range key",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Sort key 이름입니다.",
        "inputKind": "text",
        "placeholder": "createdAt"
      },
      {
        "name": "readCapacity",
        "terraformName": "read_capacity",
        "label": "Read capacity",
        "type": "number",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "PROVISIONED 모드에서 사용할 읽기 capacity입니다.",
        "inputKind": "number",
        "placeholder": "1"
      },
      {
        "name": "writeCapacity",
        "terraformName": "write_capacity",
        "label": "Write capacity",
        "type": "number",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "PROVISIONED 모드에서 사용할 쓰기 capacity입니다.",
        "inputKind": "number",
        "placeholder": "1"
      },
      {
        "name": "attribute",
        "terraformName": "attribute",
        "label": "Attributes",
        "type": "set",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Key schema에서 사용하는 attribute 정의입니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "name",
            "terraformName": "name",
            "label": "Name",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "Attribute 이름입니다.",
            "inputKind": "text",
            "placeholder": "id"
          },
          {
            "name": "type",
            "terraformName": "type",
            "label": "Type",
            "type": "string",
            "required": true,
            "optional": false,
            "computed": false,
            "sensitive": false,
            "description": "Attribute 타입입니다.",
            "inputKind": "select",
            "options": [
              "S",
              "N",
              "B"
            ]
          }
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_lambda_function": [
      {
        "name": "functionName",
        "terraformName": "function_name",
        "label": "Function name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Lambda 함수 이름입니다.",
        "inputKind": "text",
        "placeholder": "image-resizer"
      },
      {
        "name": "role",
        "terraformName": "role",
        "label": "Execution role",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Lambda 실행 역할 IAM Role입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_iam_role"
        ],
        "referenceAttribute": "arn"
      },
      {
        "name": "handler",
        "terraformName": "handler",
        "label": "Handler",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "런타임이 호출할 함수 진입점입니다.",
        "inputKind": "text",
        "placeholder": "index.handler"
      },
      {
        "name": "runtime",
        "terraformName": "runtime",
        "label": "Runtime",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Lambda 함수 런타임입니다.",
        "inputKind": "select",
        "options": [
          "nodejs22.x",
          "nodejs20.x",
          "python3.13",
          "python3.12"
        ]
      },
      {
        "name": "filename",
        "terraformName": "filename",
        "label": "Package file",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "업로드할 zip 패키지 경로입니다. 실제 업로드나 배포는 이 패널에서 실행하지 않습니다.",
        "inputKind": "text",
        "placeholder": "function.zip"
      },
      {
        "name": "timeout",
        "terraformName": "timeout",
        "label": "Timeout",
        "type": "number",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Lambda timeout입니다. 단위는 초입니다.",
        "inputKind": "number",
        "placeholder": "3"
      },
      {
        "name": "memorySize",
        "terraformName": "memory_size",
        "label": "Memory size",
        "type": "number",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Lambda 메모리 크기입니다. 단위는 MB입니다.",
        "inputKind": "number",
        "placeholder": "128"
      },
      {
        "name": "environment",
        "terraformName": "environment",
        "label": "Environment",
        "type": "list",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": true,
        "description": "환경 변수는 secret을 포함할 수 있어 값에 실제 secret을 넣지 않고 변수 참조나 placeholder를 사용합니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "variables",
            "terraformName": "variables",
            "label": "Variables",
            "type": "map",
            "required": false,
            "optional": true,
            "computed": false,
            "sensitive": true,
            "description": "Lambda 환경 변수 key-value입니다. 실제 secret 대신 var.api_key 같은 값을 사용합니다.",
            "inputKind": "key-value",
            "placeholder": "var.api_key"
          }
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_lambda_permission": [
      {
        "name": "statementId",
        "terraformName": "statement_id",
        "label": "Statement ID",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Lambda permission statement 식별자입니다.",
        "inputKind": "text",
        "placeholder": "AllowExecutionFromApiGateway"
      },
      {
        "name": "action",
        "terraformName": "action",
        "label": "Action",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "허용할 Lambda action입니다.",
        "inputKind": "select",
        "options": [
          "lambda:InvokeFunction"
        ]
      },
      {
        "name": "functionName",
        "terraformName": "function_name",
        "label": "Lambda function",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "권한을 부여할 Lambda Function입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_lambda_function"
        ],
        "referenceAttribute": "function_name"
      },
      {
        "name": "principal",
        "terraformName": "principal",
        "label": "Principal",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "호출을 허용할 AWS 서비스 principal입니다.",
        "inputKind": "text",
        "placeholder": "apigateway.amazonaws.com"
      },
      {
        "name": "sourceArn",
        "terraformName": "source_arn",
        "label": "Source ARN",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "호출을 허용할 source ARN입니다.",
        "inputKind": "text",
        "placeholder": "aws_api_gateway_rest_api.practice.execution_arn"
      }
    ],
    "aws_api_gateway_rest_api": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "API Gateway REST API 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-api"
      },
      {
        "name": "description",
        "terraformName": "description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "API의 목적을 설명합니다.",
        "inputKind": "text",
        "placeholder": "Practice REST API"
      },
      {
        "name": "apiKeySource",
        "terraformName": "api_key_source",
        "label": "API key source",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "API key를 HEADER에서 읽을지 AUTHORIZER에서 읽을지 정합니다.",
        "inputKind": "select",
        "options": [
          "HEADER",
          "AUTHORIZER"
        ]
      },
      {
        "name": "endpointConfiguration",
        "terraformName": "endpoint_configuration",
        "label": "Endpoint configuration",
        "type": "list",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "API endpoint 유형을 정합니다.",
        "inputKind": "nested-block",
        "children": [
          {
            "name": "types",
            "terraformName": "types",
            "label": "Types",
            "type": "list",
            "required": false,
            "optional": true,
            "computed": false,
            "sensitive": false,
            "description": "REST API endpoint 유형입니다.",
            "inputKind": "multi-select",
            "options": [
              "REGIONAL",
              "EDGE",
              "PRIVATE"
            ]
          }
        ]
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_api_gateway_resource": [
      {
        "name": "restApiId",
        "terraformName": "rest_api_id",
        "label": "REST API",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Resource를 생성할 REST API입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_api_gateway_rest_api"
        ]
      },
      {
        "name": "parentId",
        "terraformName": "parent_id",
        "label": "Parent ID",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "상위 API Gateway Resource ID입니다. 루트는 REST API의 root_resource_id를 사용합니다.",
        "inputKind": "text",
        "placeholder": "aws_api_gateway_rest_api.practice.root_resource_id"
      },
      {
        "name": "pathPart",
        "terraformName": "path_part",
        "label": "Path part",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "경로 segment입니다.",
        "inputKind": "text",
        "placeholder": "items"
      }
    ],
    "aws_api_gateway_method": [
      {
        "name": "restApiId",
        "terraformName": "rest_api_id",
        "label": "REST API",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Method를 연결할 REST API입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_api_gateway_rest_api"
        ]
      },
      {
        "name": "resourceId",
        "terraformName": "resource_id",
        "label": "API resource",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Method를 붙일 API Gateway Resource입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_api_gateway_resource"
        ]
      },
      {
        "name": "httpMethod",
        "terraformName": "http_method",
        "label": "HTTP method",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "클라이언트가 호출할 HTTP method입니다.",
        "inputKind": "select",
        "options": [
          "GET",
          "POST",
          "PUT",
          "PATCH",
          "DELETE",
          "ANY"
        ]
      },
      {
        "name": "authorization",
        "terraformName": "authorization",
        "label": "Authorization",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "API Gateway authorization 방식입니다.",
        "inputKind": "select",
        "options": [
          "NONE",
          "AWS_IAM",
          "CUSTOM",
          "COGNITO_USER_POOLS"
        ]
      },
      {
        "name": "apiKeyRequired",
        "terraformName": "api_key_required",
        "label": "API key required",
        "type": "boolean",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "API key가 필요한 method인지 정합니다.",
        "inputKind": "checkbox"
      }
    ],
    "aws_api_gateway_integration": [
      {
        "name": "restApiId",
        "terraformName": "rest_api_id",
        "label": "REST API",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Integration을 연결할 REST API입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_api_gateway_rest_api"
        ]
      },
      {
        "name": "resourceId",
        "terraformName": "resource_id",
        "label": "API resource",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Integration을 연결할 API Gateway Resource입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_api_gateway_resource"
        ]
      },
      {
        "name": "httpMethod",
        "terraformName": "http_method",
        "label": "HTTP method",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Integration을 연결할 API Gateway Method입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_api_gateway_method"
        ],
        "referenceAttribute": "http_method"
      },
      {
        "name": "type",
        "terraformName": "type",
        "label": "Integration type",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Backend integration 유형입니다.",
        "inputKind": "select",
        "options": [
          "AWS",
          "AWS_PROXY",
          "HTTP",
          "HTTP_PROXY",
          "MOCK"
        ]
      },
      {
        "name": "integrationHttpMethod",
        "terraformName": "integration_http_method",
        "label": "Integration HTTP method",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Lambda proxy 등 backend 호출에 사용할 HTTP method입니다.",
        "inputKind": "select",
        "options": [
          "POST",
          "GET",
          "ANY"
        ]
      },
      {
        "name": "uri",
        "terraformName": "uri",
        "label": "URI",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Backend endpoint 또는 Lambda invoke ARN입니다.",
        "inputKind": "text",
        "placeholder": "aws_lambda_function.handler.invoke_arn"
      }
    ],
    "aws_cloudwatch_log_group": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "CloudWatch Log Group 이름입니다.",
        "inputKind": "text",
        "placeholder": "/aws/lambda/practice"
      },
      {
        "name": "retentionInDays",
        "terraformName": "retention_in_days",
        "label": "Retention days",
        "type": "number",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "로그 보관 일수입니다.",
        "inputKind": "number",
        "placeholder": "14"
      },
      {
        "name": "kmsKeyId",
        "terraformName": "kms_key_id",
        "label": "KMS key",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "로그 암호화에 사용할 KMS Key입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_kms_key"
        ],
        "referenceAttribute": "arn"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_cloudwatch_metric_alarm": [
      {
        "name": "alarmName",
        "terraformName": "alarm_name",
        "label": "Alarm name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "CloudWatch Alarm 이름입니다.",
        "inputKind": "text",
        "placeholder": "high-cpu"
      },
      {
        "name": "namespace",
        "terraformName": "namespace",
        "label": "Namespace",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Metric namespace입니다.",
        "inputKind": "text",
        "placeholder": "AWS/EC2"
      },
      {
        "name": "metricName",
        "terraformName": "metric_name",
        "label": "Metric name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "감시할 metric 이름입니다.",
        "inputKind": "text",
        "placeholder": "CPUUtilization"
      },
      {
        "name": "comparisonOperator",
        "terraformName": "comparison_operator",
        "label": "Comparison",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "알람 조건 비교 연산자입니다.",
        "inputKind": "select",
        "options": [
          "GreaterThanThreshold",
          "GreaterThanOrEqualToThreshold",
          "LessThanThreshold",
          "LessThanOrEqualToThreshold"
        ]
      },
      {
        "name": "threshold",
        "terraformName": "threshold",
        "label": "Threshold",
        "type": "number",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "알람 threshold입니다.",
        "inputKind": "number",
        "placeholder": "80"
      },
      {
        "name": "evaluationPeriods",
        "terraformName": "evaluation_periods",
        "label": "Evaluation periods",
        "type": "number",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "평가 기간 개수입니다.",
        "inputKind": "number",
        "placeholder": "2"
      },
      {
        "name": "period",
        "terraformName": "period",
        "label": "Period",
        "type": "number",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Metric period입니다. 단위는 초입니다.",
        "inputKind": "number",
        "placeholder": "300"
      },
      {
        "name": "statistic",
        "terraformName": "statistic",
        "label": "Statistic",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "집계 방식입니다.",
        "inputKind": "select",
        "options": [
          "Average",
          "Maximum",
          "Minimum",
          "Sum"
        ]
      },
      {
        "name": "alarmActions",
        "terraformName": "alarm_actions",
        "label": "Alarm actions",
        "type": "set",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "알람 발생 시 알림을 보낼 SNS Topic입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_sns_topic"
        ],
        "referenceAttribute": "arn"
      }
    ],
    "aws_cloudwatch_dashboard": [
      {
        "name": "dashboardName",
        "terraformName": "dashboard_name",
        "label": "Dashboard name",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "CloudWatch Dashboard 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-dashboard"
      },
      {
        "name": "dashboardBody",
        "terraformName": "dashboard_body",
        "label": "Dashboard body",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Dashboard body JSON입니다. MVP에서는 text로 입력합니다.",
        "inputKind": "text",
        "placeholder": "placeholder:cloudwatch_dashboard_body_json"
      }
    ],
    "aws_cloudwatch_event_rule": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "EventBridge Rule 이름입니다.",
        "inputKind": "text",
        "placeholder": "daily-practice"
      },
      {
        "name": "scheduleExpression",
        "terraformName": "schedule_expression",
        "label": "Schedule expression",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "스케줄 기반 rule일 때 사용할 표현식입니다.",
        "inputKind": "text",
        "placeholder": "rate(1 day)"
      },
      {
        "name": "eventPattern",
        "terraformName": "event_pattern",
        "label": "Event pattern",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "이벤트 패턴 JSON입니다. MVP에서는 text로 입력합니다.",
        "inputKind": "text",
        "placeholder": "placeholder:event_pattern_json"
      },
      {
        "name": "description",
        "terraformName": "description",
        "label": "Description",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Rule의 목적입니다.",
        "inputKind": "text",
        "placeholder": "Runs a practice Lambda every day"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ],
    "aws_cloudwatch_event_target": [
      {
        "name": "rule",
        "terraformName": "rule",
        "label": "Event rule",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Target을 연결할 EventBridge Rule입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_cloudwatch_event_rule"
        ],
        "referenceAttribute": "name"
      },
      {
        "name": "arn",
        "terraformName": "arn",
        "label": "Target ARN",
        "type": "string",
        "required": true,
        "optional": false,
        "computed": false,
        "sensitive": false,
        "description": "Event target으로 호출할 Lambda 또는 SNS Topic입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_lambda_function",
          "aws_sns_topic"
        ],
        "referenceAttribute": "arn"
      },
      {
        "name": "targetId",
        "terraformName": "target_id",
        "label": "Target ID",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "Event target 식별자입니다.",
        "inputKind": "text",
        "placeholder": "lambda-target"
      }
    ],
    "aws_sns_topic": [
      {
        "name": "name",
        "terraformName": "name",
        "label": "Name",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": true,
        "sensitive": false,
        "description": "SNS Topic 이름입니다.",
        "inputKind": "text",
        "placeholder": "practice-alerts"
      },
      {
        "name": "kmsMasterKeyId",
        "terraformName": "kms_master_key_id",
        "label": "KMS key",
        "type": "string",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "Topic 암호화에 사용할 KMS Key입니다.",
        "inputKind": "reference-picker",
        "referenceTargetTypes": [
          "aws_kms_key"
        ],
        "referenceAttribute": "arn"
      },
      {
        "name": "tags",
        "terraformName": "tags",
        "label": "Tags",
        "type": "map",
        "required": false,
        "optional": true,
        "computed": false,
        "sensitive": false,
        "description": "AWS 콘솔과 비용 추적에서 리소스를 구분하기 위한 key-value 태그입니다.",
        "inputKind": "key-value"
      }
    ]
  }
} satisfies ParameterCatalog;

export const terraformParameterCatalog = terraformAwsParameterCatalog;
export type { ParameterCatalog, ParameterCatalogDefinition } from "./catalog-overrides";
