import {
  adaptBrainboardTemplateSource,
  brainboardTemplateRegistry,
  buildTemplateDiagramJson,
  templateDefinitions
} from "@sketchcatch/types";
import {
  ARCHITECTURE_BOARD_KNOWLEDGE_VERSION,
  type ArchitectureBoardKnowledgeArtifact
} from "./architecture-board-knowledge-contract";
import { extractArchitectureBoardKnowledgeCase } from "./architecture-board-knowledge-metrics";
import {
  extractArchitectureBoardModulePatterns,
  type ArchitectureBoardModulePatternSourceDiagram
} from "./architecture-board-module-pattern-source";

export function createArchitectureBoardKnowledgeArtifactFromSource(): ArchitectureBoardKnowledgeArtifact {
  const repositorySources: ArchitectureBoardModulePatternSourceDiagram[] = templateDefinitions.map(
    (definition) => ({
      id: `repository:${definition.id}`,
      diagram: buildTemplateDiagramJson(definition.id, {
        projectSlug: "compiler-knowledge",
        shortId: definition.id
      })
    })
  );
  const brainboardSources: ArchitectureBoardModulePatternSourceDiagram[] =
    brainboardTemplateRegistry.flatMap((entry) =>
      entry.status === "available"
        ? [
            {
              id: `brainboard:${entry.id}`,
              diagram: adaptBrainboardTemplateSource(entry.source).diagramJson
            }
          ]
        : []
    );
  const unavailableTemplateIds = brainboardTemplateRegistry.flatMap((entry) =>
    entry.status === "unavailable" ? [entry.id] : []
  );
  const sources = [...repositorySources, ...brainboardSources];
  const cases = sources
    .map(({ id, diagram }) => extractArchitectureBoardKnowledgeCase(id, diagram))
    .sort((left, right) => left.id.localeCompare(right.id));
  const modulePatterns = extractArchitectureBoardModulePatterns(sources);
  const content = stableSerialize({
    cases,
    modulePatterns,
    unavailableTemplateIds,
    version: ARCHITECTURE_BOARD_KNOWLEDGE_VERSION
  });

  return {
    version: ARCHITECTURE_BOARD_KNOWLEDGE_VERSION,
    hash: fnv1a(content),
    cases,
    modulePatterns,
    unavailableTemplateIds
  };
}

export function renderArchitectureBoardKnowledgeArtifact(
  artifact: ArchitectureBoardKnowledgeArtifact
): string {
  return [
    "// Generated by `pnpm architecture-board-knowledge:generate`.",
    "// Do not edit manually. Run the generator after changing a source template fixture.",
    "import {",
    "  ARCHITECTURE_BOARD_KNOWLEDGE_VERSION,",
    '  type ArchitectureBoardKnowledgeArtifact\n} from "./architecture-board-knowledge-contract";',
    "",
    "export const generatedArchitectureBoardKnowledgeArtifact = {",
    "  version: ARCHITECTURE_BOARD_KNOWLEDGE_VERSION,",
    `  hash: ${JSON.stringify(artifact.hash)},`,
    `  cases: ${indentJson(JSON.stringify(artifact.cases, null, 2), 2)},`,
    `  modulePatterns: ${indentJson(JSON.stringify(artifact.modulePatterns, null, 2), 2)},`,
    `  unavailableTemplateIds: ${indentJson(JSON.stringify(artifact.unavailableTemplateIds, null, 2), 2)}`,
    "} as const satisfies ArchitectureBoardKnowledgeArtifact;",
    ""
  ].join("\n");
}

function indentJson(value: string, spaces: number): string {
  return value.replaceAll("\n", `\n${" ".repeat(spaces)}`);
}

function stableSerialize(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(stableSerialize).join(",")}]`;
  }
  if (value !== null && typeof value === "object") {
    return `{${Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, entry]) => `${JSON.stringify(key)}:${stableSerialize(entry)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function fnv1a(value: string): string {
  let hash = 0x811c9dc5;

  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }

  return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`;
}
