import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

const currentDir = dirname(fileURLToPath(import.meta.url));
const resourceTypeLabelsPath = join(currentDir, "resource-type-labels.ts");

test("getResourceTypeLabel displays internal resource types as readable labels", () => {
	const resourceTypeLabelsSource = readFileSync(resourceTypeLabelsPath, "utf8");

	assert.match(resourceTypeLabelsSource, /SECURITY_GROUP:\s*"Security Group"/);
	assert.match(resourceTypeLabelsSource, /INTERNET_GATEWAY:\s*"Internet Gateway"/);
	assert.match(resourceTypeLabelsSource, /ROUTE_TABLE:\s*"Route Table"/);
	assert.match(resourceTypeLabelsSource, /ROUTE_TABLE_ASSOCIATION:\s*"Route Table Association"/);
	assert.match(resourceTypeLabelsSource, /CLOUDFRONT:\s*"CloudFront"/);
	assert.match(resourceTypeLabelsSource, /EC2:\s*"EC2"/);
	assert.match(resourceTypeLabelsSource, /AMI:\s*"AMI"/);
	assert.match(resourceTypeLabelsSource, /IAM_ROLE:\s*"IAM Role"/);
	assert.match(resourceTypeLabelsSource, /IAM_POLICY:\s*"IAM Policy"/);
	assert.match(resourceTypeLabelsSource, /IAM_INSTANCE_PROFILE:\s*"IAM Instance Profile"/);
	assert.match(resourceTypeLabelsSource, /KMS_KEY:\s*"KMS Key"/);
	assert.match(resourceTypeLabelsSource, /CLOUDWATCH_LOG_GROUP:\s*"CloudWatch Log Group"/);
	assert.match(resourceTypeLabelsSource, /CLOUDWATCH_METRIC_ALARM:\s*"CloudWatch Metric Alarm"/);
	assert.match(resourceTypeLabelsSource, /API_GATEWAY_REST_API:\s*"API Gateway REST API"/);
	assert.match(resourceTypeLabelsSource, /LAMBDA_PERMISSION:\s*"Lambda Permission"/);
	assert.match(resourceTypeLabelsSource, /RDS:\s*"RDS"/);
	assert.match(resourceTypeLabelsSource, /AUTO_SCALING_GROUP:\s*"Auto Scaling Group"/);
	assert.match(resourceTypeLabelsSource, /LAUNCH_TEMPLATE:\s*"Launch Template"/);
	assert.match(resourceTypeLabelsSource, /LOAD_BALANCER_TARGET_GROUP:\s*"Load Balancer Target Group"/);
	assert.match(resourceTypeLabelsSource, /NAT_GATEWAY:\s*"NAT Gateway"/);
	assert.match(resourceTypeLabelsSource, /ELASTIC_IP:\s*"Elastic IP"/);
	assert.match(resourceTypeLabelsSource, /DYNAMODB_TABLE:\s*"DynamoDB Table"/);
	assert.match(resourceTypeLabelsSource, /API_GATEWAY_WEBSOCKET_API:\s*"API Gateway WebSocket API"/);
	assert.match(resourceTypeLabelsSource, /SNS_TOPIC:\s*"SNS Topic"/);
	assert.match(resourceTypeLabelsSource, /SQS_QUEUE:\s*"SQS Queue"/);
	assert.match(resourceTypeLabelsSource, /EVENTBRIDGE_RULE:\s*"EventBridge Rule"/);
	assert.match(resourceTypeLabelsSource, /EVENTBRIDGE_TARGET:\s*"EventBridge Target"/);
	assert.match(resourceTypeLabelsSource, /ELASTICACHE_REDIS:\s*"ElastiCache Redis"/);
	assert.match(resourceTypeLabelsSource, /ACM_CERTIFICATE:\s*"ACM Certificate"/);
	assert.match(resourceTypeLabelsSource, /CLOUDWATCH_DASHBOARD:\s*"CloudWatch Dashboard"/);
	assert.match(resourceTypeLabelsSource, /RDS_READ_REPLICA:\s*"RDS Read Replica"/);
	assert.match(resourceTypeLabelsSource, /RDS_CLUSTER:\s*"RDS Cluster"/);
	assert.match(resourceTypeLabelsSource, /EBS_VOLUME:\s*"EBS Volume"/);
	assert.match(resourceTypeLabelsSource, /KEY_PAIR:\s*"Key Pair"/);
	assert.match(resourceTypeLabelsSource, /API_GATEWAY_RESOURCE:\s*"API Gateway Resource"/);
	assert.match(resourceTypeLabelsSource, /API_GATEWAY_METHOD:\s*"API Gateway Method"/);
	assert.match(resourceTypeLabelsSource, /API_GATEWAY_INTEGRATION:\s*"API Gateway Integration"/);
	assert.match(resourceTypeLabelsSource, /API_GATEWAY_STAGE:\s*"API Gateway Stage"/);
	assert.match(resourceTypeLabelsSource, /STEP_FUNCTIONS_STATE_MACHINE:\s*"Step Functions State Machine"/);
	assert.match(resourceTypeLabelsSource, /LAMBDA_EVENT_SOURCE_MAPPING:\s*"Lambda Event Source Mapping"/);
	assert.match(resourceTypeLabelsSource, /COGNITO_USER_POOL:\s*"Cognito User Pool"/);
	assert.match(resourceTypeLabelsSource, /COGNITO_USER_POOL_CLIENT:\s*"Cognito User Pool Client"/);
	assert.match(resourceTypeLabelsSource, /ECR_REPOSITORY:\s*"ECR Repository"/);
	assert.match(resourceTypeLabelsSource, /ECS_CLUSTER:\s*"ECS Cluster"/);
	assert.match(resourceTypeLabelsSource, /ECS_SERVICE:\s*"ECS Service"/);
	assert.match(resourceTypeLabelsSource, /ECS_TASK_DEFINITION:\s*"ECS Task Definition"/);
	assert.match(resourceTypeLabelsSource, /EKS_CLUSTER:\s*"EKS Cluster"/);
});
