import type { ResourceType } from "@sketchcatch/types";

const resourceTypeLabels: Record<ResourceType, string> = {
	VPC: "VPC",
	SUBNET: "Subnet",
	INTERNET_GATEWAY: "Internet Gateway",
	ROUTE_TABLE: "Route Table",
	ROUTE_TABLE_ASSOCIATION: "Route Table Association",
	NAT_GATEWAY: "NAT Gateway",
	EC2: "EC2",
	AUTO_SCALING_GROUP: "Auto Scaling Group",
	LAUNCH_TEMPLATE: "Launch Template",
	KEY_PAIR: "Key Pair",
	ELASTIC_IP: "Elastic IP",
	EBS_VOLUME: "EBS Volume",
	RDS: "RDS",
	RDS_READ_REPLICA: "RDS Read Replica",
	RDS_CLUSTER: "RDS Cluster",
	S3: "S3",
	DYNAMODB_TABLE: "DynamoDB Table",
	ELASTICACHE_REDIS: "ElastiCache Redis",
	SECURITY_GROUP: "Security Group",
	CLOUDFRONT: "CloudFront",
	LOAD_BALANCER_TARGET_GROUP: "Load Balancer Target Group",
	LAMBDA: "Lambda",
	LAMBDA_EVENT_SOURCE_MAPPING: "Lambda Event Source Mapping",
	AMI: "AMI",
	IAM_ROLE: "IAM Role",
	IAM_POLICY: "IAM Policy",
	IAM_INSTANCE_PROFILE: "IAM Instance Profile",
	KMS_KEY: "KMS Key",
	ACM_CERTIFICATE: "ACM Certificate",
	COGNITO_USER_POOL: "Cognito User Pool",
	COGNITO_USER_POOL_CLIENT: "Cognito User Pool Client",
	CLOUDWATCH_LOG_GROUP: "CloudWatch Log Group",
	CLOUDWATCH_METRIC_ALARM: "CloudWatch Metric Alarm",
	CLOUDWATCH_DASHBOARD: "CloudWatch Dashboard",
	API_GATEWAY_REST_API: "API Gateway REST API",
	API_GATEWAY_WEBSOCKET_API: "API Gateway WebSocket API",
	API_GATEWAY_RESOURCE: "API Gateway Resource",
	API_GATEWAY_METHOD: "API Gateway Method",
	API_GATEWAY_INTEGRATION: "API Gateway Integration",
	API_GATEWAY_STAGE: "API Gateway Stage",
	LAMBDA_PERMISSION: "Lambda Permission",
	SNS_TOPIC: "SNS Topic",
	SQS_QUEUE: "SQS Queue",
	EVENTBRIDGE_RULE: "EventBridge Rule",
	EVENTBRIDGE_TARGET: "EventBridge Target",
	STEP_FUNCTIONS_STATE_MACHINE: "Step Functions State Machine",
	ECR_REPOSITORY: "ECR Repository",
	ECS_CLUSTER: "ECS Cluster",
	ECS_SERVICE: "ECS Service",
	ECS_TASK_DEFINITION: "ECS Task Definition",
	EKS_CLUSTER: "EKS Cluster",
	UNKNOWN: "Unknown"
};

// 내부 ResourceType 값을 화면에 보여줄 짧은 이름으로 바꿉니다.
export function getResourceTypeLabel(resourceType: ResourceType): string {
	return resourceTypeLabels[resourceType];
}
