import type { ResourceType } from "@sketchcatch/types";

const resourceTypeLabels: Record<ResourceType, string> = {
  VPC: "VPC",
  SUBNET: "Subnet",
  INTERNET_GATEWAY: "Internet Gateway",
  ROUTE_TABLE: "Route Table",
  ROUTE_TABLE_ASSOCIATION: "Route Table Association",
  NETWORK_ACL: "Network ACL",
  NETWORK_ACL_RULE: "Network ACL Rule",
  VPC_PEERING_CONNECTION: "VPC Peering Connection",
  NAT_GATEWAY: "NAT Gateway",
  EC2: "EC2",
  AUTO_SCALING_GROUP: "Auto Scaling Group",
  LAUNCH_TEMPLATE: "Launch Template",
  KEY_PAIR: "Key Pair",
  ELASTIC_IP: "Elastic IP",
  EBS_VOLUME: "EBS Volume",
  VOLUME_ATTACHMENT: "Volume Attachment",
  EFS_FILE_SYSTEM: "EFS File System",
  EFS_MOUNT_TARGET: "EFS Mount Target",
  EFS_ACCESS_POINT: "EFS Access Point",
  RDS: "RDS",
  RDS_READ_REPLICA: "RDS Read Replica",
  RDS_CLUSTER: "RDS Cluster",
  RDS_CLUSTER_INSTANCE: "RDS Cluster Instance",
  S3: "S3",
  DYNAMODB_TABLE: "DynamoDB Table",
  ELASTICACHE_REDIS: "ElastiCache Redis",
  ELASTICACHE_SUBNET_GROUP: "ElastiCache Subnet Group",
  ELASTICACHE_PARAMETER_GROUP: "ElastiCache Parameter Group",
  SECURITY_GROUP: "Security Group",
  CLOUDFRONT: "CloudFront",
  LOAD_BALANCER_TARGET_GROUP: "Load Balancer Target Group",
  LOAD_BALANCER_TARGET_GROUP_ATTACHMENT: "Load Balancer Target Group Attachment",
  ROUTE53_RECORD: "Route 53 Record",
  ROUTE53_ZONE: "Route 53 Zone",
  WAF_WEB_ACL: "WAF Web ACL",
  WAF_WEB_ACL_ASSOCIATION: "WAF Web ACL Association",
  LOAD_BALANCER: "Load Balancer",
  LOAD_BALANCER_LISTENER: "Load Balancer Listener",
  LAMBDA: "Lambda",
  LAMBDA_ALIAS: "Lambda Alias",
  LAMBDA_EVENT_SOURCE_MAPPING: "Lambda Event Source Mapping",
  AMI: "AMI",
  IAM_ROLE: "IAM Role",
  IAM_POLICY: "IAM Policy",
  IAM_INSTANCE_PROFILE: "IAM Instance Profile",
  KMS_KEY: "KMS Key",
  KMS_ALIAS: "KMS Alias",
  ACM_CERTIFICATE: "ACM Certificate",
  ACM_CERTIFICATE_VALIDATION: "ACM Certificate Validation",
  COGNITO_USER_POOL: "Cognito User Pool",
  COGNITO_USER_POOL_CLIENT: "Cognito User Pool Client",
  DB_SUBNET_GROUP: "DB Subnet Group",
  SECRETS_MANAGER_SECRET: "Secrets Manager Secret",
  VPC_ENDPOINT: "VPC Endpoint",
  CLOUDWATCH_LOG_GROUP: "CloudWatch Log Group",
  CLOUDWATCH_LOG_STREAM: "CloudWatch Log Stream",
  CLOUDWATCH_METRIC_ALARM: "CloudWatch Metric Alarm",
  CLOUDWATCH_DASHBOARD: "CloudWatch Dashboard",
  CLOUDWATCH_LOG_RESOURCE_POLICY: "CloudWatch Log Resource Policy",
  CLOUDTRAIL: "CloudTrail",
  XRAY_GROUP: "X-Ray Group",
  XRAY_SAMPLING_RULE: "X-Ray Sampling Rule",
  API_GATEWAY_REST_API: "API Gateway REST API",
  API_GATEWAY_WEBSOCKET_API: "API Gateway WebSocket API",
  API_GATEWAY_RESOURCE: "API Gateway Resource",
  API_GATEWAY_METHOD: "API Gateway Method",
  API_GATEWAY_INTEGRATION: "API Gateway Integration",
  API_GATEWAY_DEPLOYMENT: "API Gateway Deployment",
  API_GATEWAY_STAGE: "API Gateway Stage",
  API_GATEWAY_V2_ROUTE: "API Gateway V2 Route",
  API_GATEWAY_V2_INTEGRATION: "API Gateway V2 Integration",
  API_GATEWAY_V2_STAGE: "API Gateway V2 Stage",
  LAMBDA_PERMISSION: "Lambda Permission",
  SNS_TOPIC: "SNS Topic",
  SNS_TOPIC_SUBSCRIPTION: "SNS Topic Subscription",
  SQS_QUEUE: "SQS Queue",
  EVENTBRIDGE_RULE: "EventBridge Rule",
  EVENTBRIDGE_TARGET: "EventBridge Target",
  EVENTBRIDGE_PERMISSION: "EventBridge Permission",
  SCHEDULER_SCHEDULE: "Scheduler Schedule",
  STEP_FUNCTIONS_STATE_MACHINE: "Step Functions State Machine",
  ECR_REPOSITORY: "ECR Repository",
  ECR_LIFECYCLE_POLICY: "ECR Lifecycle Policy",
  ECS_CLUSTER: "ECS Cluster",
  ECS_SERVICE: "ECS Service",
  ECS_TASK_DEFINITION: "ECS Task Definition",
  ECS_CAPACITY_PROVIDER: "ECS Capacity Provider",
  EKS_CLUSTER: "EKS Cluster",
  EKS_NODE_GROUP: "EKS Node Group",
  EKS_ADDON: "EKS Add-on",
  CONFIG_CONFIGURATION_RECORDER: "AWS Config Recorder",
  CONFIG_DELIVERY_CHANNEL: "AWS Config Delivery Channel",
  CONFIG_RULE: "AWS Config Rule",
  SHIELD_PROTECTION: "Shield Protection",
  GUARDDUTY_DETECTOR: "GuardDuty Detector",
  UNKNOWN: "Unknown"
};

// 내부 ResourceType 값을 화면에 보여줄 짧은 이름으로 바꿉니다.
export function getResourceTypeLabel(resourceType: ResourceType): string {
  return resourceTypeLabels[resourceType];
}
