export const SKETCHCATCH_REFERENCE_TERRAFORM_MARKER = "sketchcatch-reference-web-service-deployment";

export const SKETCHCATCH_REFERENCE_TERRAFORM_CODE = [
  "resource \"aws_vpc\" \"vpc\" {",
  "  tags                 = merge(var.tags, { Name = \"sketchcatch-vpc\" })",
  "  region               = \"ap-northeast-2\"",
  "  enable_dns_support   = true",
  "  enable_dns_hostnames = true",
  "  cidr_block           = \"10.0.0.0/16\"",
  "}",
  "",
  "resource \"aws_autoscaling_group\" \"autoscaling_group\" {",
  "  region            = \"ap-northeast-2\"",
  "  name              = \"sketchcatch-asg\"",
  "  min_size          = 2",
  "  max_size          = 4",
  "  health_check_type = \"ELB\"",
  "  desired_capacity  = 2",
  "",
  "  vpc_zone_identifier = [",
  "    aws_subnet.snet2.id,",
  "    aws_subnet.snet3.id,",
  "  ]",
  "",
  "  target_group_arns = [",
  "    aws_lb_target_group.lb_target_group.arn,",
  "  ]",
  "",
  "  depends_on = [",
  "    aws_route.private_app_a_default_route,",
  "    aws_route.private_app_c_default_route,",
  "    aws_lb_listener.http_listener,",
  "    aws_iam_role_policy_attachment.ec2_ssm,",
  "    aws_iam_role_policy_attachment.ec2_codedeploy,",
  "  ]",
  "",
  "  launch_template {",
  "    version = \"$Latest\"",
  "    id      = aws_launch_template.launch_template.id",
  "  }",
  "",
  "  tag {",
  "    value               = \"sketchcatch-api\"",
  "    propagate_at_launch = true",
  "    key                 = \"Name\"",
  "  }",
  "}",
  "",
  "resource \"aws_subnet\" \"snet2\" {",
  "  vpc_id            = aws_vpc.vpc.id",
  "  tags              = merge(var.tags, { Name = \"private-app-a\" })",
  "  region            = \"ap-northeast-2\"",
  "  cidr_block        = \"10.0.10.0/24\"",
  "  availability_zone = \"ap-northeast-2a\"",
  "}",
  "",
  "resource \"aws_internet_gateway\" \"internet_gw\" {",
  "  vpc_id = aws_vpc.vpc.id",
  "  tags   = merge(var.tags, { Name = \"sketchcatch-igw\" })",
  "  region = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_s3_bucket\" \"s3_bucket\" {",
  "  tags          = merge(var.tags, { Name = \"static-frontend-s3\" })",
  "  region        = \"ap-northeast-2\"",
  "  force_destroy = true",
  "  bucket        = \"sketchcatch-static-${data.aws_caller_identity.current.account_id}\"",
  "}",
  "",
  "resource \"aws_db_instance\" \"db_instance\" {",
  "  username             = \"admin\"",
  "  tags                 = merge(var.tags, { Name = \"rds-primary-standby\" })",
  "  skip_final_snapshot  = true",
  "  region               = \"ap-northeast-2\"",
  "  publicly_accessible  = false",
  "  password             = random_password.db_password.result",
  "  multi_az             = true",
  "  instance_class       = \"db.t4g.micro\"",
  "  identifier           = \"sketchcatch-db\"",
  "  engine_version       = \"8.0\"",
  "  engine               = \"mysql\"",
  "  db_subnet_group_name = aws_db_subnet_group.db_snet_group.name",
  "  db_name              = \"sketchcatch\"",
  "  allocated_storage    = 20",
  "",
  "  vpc_security_group_ids = [",
  "    aws_security_group.sg3.id,",
  "  ]",
  "}",
  "",
  "resource \"aws_security_group\" \"sg3\" {",
  "  vpc_id = aws_vpc.vpc.id",
  "  tags   = merge(var.tags, { Name = \"rds-sg\" })",
  "  region = \"ap-northeast-2\"",
  "  name   = \"rds-sg\"",
  "}",
  "",
  "resource \"aws_security_group_rule\" \"sg_rule3\" {",
  "  type                     = \"ingress\"",
  "  to_port                  = 3306",
  "  source_security_group_id = aws_security_group.sg6.id",
  "  security_group_id        = aws_security_group.sg3.id",
  "  region                   = \"ap-northeast-2\"",
  "  protocol                 = \"tcp\"",
  "  from_port                = 3306",
  "}",
  "",
  "resource \"aws_cloudfront_distribution\" \"cloudfront_distribution\" {",
  "  tags                = merge(var.tags, { Name = \"sketchcatch-cloudfront\" })",
  "  enabled             = true",
  "  default_root_object = \"index.html\"",
  "",
  "  default_cache_behavior {",
  "    viewer_protocol_policy = \"redirect-to-https\"",
  "    target_origin_id       = \"static-frontend-s3\"",
  "",
  "    cached_methods = [",
  "      \"GET\",",
  "      \"HEAD\",",
  "    ]",
  "",
  "    allowed_methods = [",
  "      \"GET\",",
  "      \"HEAD\",",
  "    ]",
  "",
  "    forwarded_values {",
  "      query_string = false",
  "",
  "      cookies {",
  "        forward = \"none\"",
  "      }",
  "    }",
  "  }",
  "",
  "  ordered_cache_behavior {",
  "    viewer_protocol_policy = \"redirect-to-https\"",
  "    target_origin_id       = \"api-alb\"",
  "    path_pattern           = \"/api/*\"",
  "    min_ttl                = 0",
  "    max_ttl                = 0",
  "    default_ttl            = 0",
  "",
  "    cached_methods = [",
  "      \"GET\",",
  "      \"HEAD\",",
  "    ]",
  "",
  "    allowed_methods = [",
  "      \"GET\",",
  "      \"HEAD\",",
  "      \"OPTIONS\",",
  "      \"PUT\",",
  "      \"POST\",",
  "      \"PATCH\",",
  "      \"DELETE\",",
  "    ]",
  "",
  "    forwarded_values {",
  "      query_string = true",
  "",
  "      headers = [",
  "        \"*\",",
  "      ]",
  "",
  "      cookies {",
  "        forward = \"all\"",
  "      }",
  "    }",
  "  }",
  "",
  "  origin {",
  "    origin_id                = \"static-frontend-s3\"",
  "    origin_access_control_id = aws_cloudfront_origin_access_control.s3_oac.id",
  "    domain_name              = aws_s3_bucket.s3_bucket.bucket_regional_domain_name",
  "",
  "    s3_origin_config {",
  "      origin_access_identity = \"\"",
  "    }",
  "  }",
  "",
  "  origin {",
  "    origin_id   = \"api-alb\"",
  "    domain_name = aws_lb.lb.dns_name",
  "",
  "    custom_origin_config {",
  "      origin_protocol_policy = \"http-only\"",
  "      https_port             = 443",
  "      http_port              = 80",
  "",
  "      origin_ssl_protocols = [",
  "        \"TLSv1.2\",",
  "      ]",
  "    }",
  "  }",
  "",
  "  restrictions {",
  "    geo_restriction {",
  "      restriction_type = \"none\"",
  "    }",
  "  }",
  "",
  "  viewer_certificate {",
  "    cloudfront_default_certificate = true",
  "  }",
  "}",
  "",
  "resource \"aws_instance\" \"instance2\" {",
  "  tags                 = merge(var.tags, { Name = \"disabled-direct-instance-a\" })",
  "  subnet_id            = aws_subnet.snet2.id",
  "  region               = \"ap-northeast-2\"",
  "  instance_type        = \"t3.micro\"",
  "  iam_instance_profile = aws_iam_instance_profile.ec2_instance_profile.name",
  "  count                = 0",
  "  ami                  = data.aws_ssm_parameter.al2023_ami.value",
  "",
  "  vpc_security_group_ids = [",
  "    aws_security_group.sg6.id,",
  "  ]",
  "}",
  "",
  "resource \"aws_security_group\" \"sg6\" {",
  "  vpc_id = aws_vpc.vpc.id",
  "  tags   = merge(var.tags, { Name = \"app-sg\" })",
  "  region = \"ap-northeast-2\"",
  "  name   = \"app-sg\"",
  "}[오전 2:50]resource \"aws_security_group_rule\" \"sg_rule6\" {",
  "  type                     = \"ingress\"",
  "  to_port                  = 8080",
  "  source_security_group_id = aws_security_group.sg.id",
  "  security_group_id        = aws_security_group.sg6.id",
  "  region                   = \"ap-northeast-2\"",
  "  protocol                 = \"tcp\"",
  "  from_port                = 8080",
  "}",
  "",
  "resource \"aws_db_subnet_group\" \"db_snet_group\" {",
  "  tags   = merge(var.tags, { Name = \"db-subnet-group\" })",
  "  region = \"ap-northeast-2\"",
  "  name   = \"sketchcatch-db-subnet-group\"",
  "",
  "  subnet_ids = [",
  "    aws_subnet.snet7.id,",
  "    aws_subnet.snet6.id,",
  "  ]",
  "}",
  "",
  "resource \"aws_lb\" \"lb\" {",
  "  tags               = merge(var.tags, { Name = \"api-alb\" })",
  "  region             = \"ap-northeast-2\"",
  "  name               = \"sketchcatch-alb\"",
  "  load_balancer_type = \"application\"",
  "  internal           = false",
  "",
  "  subnets = [",
  "    aws_subnet.snet4.id,",
  "    aws_subnet.snet5.id,",
  "  ]",
  "",
  "  security_groups = [",
  "    aws_security_group.sg.id,",
  "  ]",
  "}",
  "",
  "resource \"aws_subnet\" \"snet3\" {",
  "  vpc_id            = aws_vpc.vpc.id",
  "  tags              = merge(var.tags, { Name = \"private-app-c\" })",
  "  region            = \"ap-northeast-2\"",
  "  cidr_block        = \"10.0.11.0/24\"",
  "  availability_zone = \"ap-northeast-2c\"",
  "}",
  "",
  "resource \"aws_instance\" \"instance3\" {",
  "  tags                 = merge(var.tags, { Name = \"disabled-direct-instance-c\" })",
  "  subnet_id            = aws_subnet.snet3.id",
  "  region               = \"ap-northeast-2\"",
  "  instance_type        = \"t3.micro\"",
  "  iam_instance_profile = aws_iam_instance_profile.ec2_instance_profile.name",
  "  count                = 0",
  "  ami                  = data.aws_ssm_parameter.al2023_ami.value",
  "",
  "  vpc_security_group_ids = [",
  "    aws_security_group.sg6.id,",
  "  ]",
  "}",
  "",
  "resource \"aws_subnet\" \"snet4\" {",
  "  vpc_id                  = aws_vpc.vpc.id",
  "  tags                    = merge(var.tags, { Name = \"public-a\" })",
  "  region                  = \"ap-northeast-2\"",
  "  map_public_ip_on_launch = true",
  "  cidr_block              = \"10.0.0.0/24\"",
  "  availability_zone       = \"ap-northeast-2a\"",
  "}",
  "",
  "resource \"aws_security_group\" \"sg\" {",
  "  vpc_id = aws_vpc.vpc.id",
  "  tags   = merge(var.tags, { Name = \"alb-sg\" })",
  "  region = \"ap-northeast-2\"",
  "  name   = \"alb-sg\"",
  "}",
  "",
  "resource \"aws_security_group_rule\" \"sg_rule\" {",
  "  type              = \"ingress\"",
  "  to_port           = 80",
  "  security_group_id = aws_security_group.sg.id",
  "  region            = \"ap-northeast-2\"",
  "  protocol          = \"tcp\"",
  "  from_port         = 80",
  "",
  "  cidr_blocks = [",
  "    \"0.0.0.0/0\",",
  "  ]",
  "}",
  "",
  "resource \"aws_subnet\" \"snet6\" {",
  "  vpc_id            = aws_vpc.vpc.id",
  "  tags              = merge(var.tags, { Name = \"private-db-c\" })",
  "  region            = \"ap-northeast-2\"",
  "  cidr_block        = \"10.0.21.0/24\"",
  "  availability_zone = \"ap-northeast-2c\"",
  "}",
  "",
  "resource \"aws_subnet\" \"snet7\" {",
  "  vpc_id            = aws_vpc.vpc.id",
  "  tags              = merge(var.tags, { Name = \"private-db-a\" })",
  "  region            = \"ap-northeast-2\"",
  "  cidr_block        = \"10.0.20.0/24\"",
  "  availability_zone = \"ap-northeast-2a\"",
  "}",
  "",
  "resource \"aws_subnet\" \"snet5\" {",
  "  vpc_id                  = aws_vpc.vpc.id",
  "  tags                    = merge(var.tags, { Name = \"public-b\" })",
  "  region                  = \"ap-northeast-2\"",
  "  map_public_ip_on_launch = true",
  "  cidr_block              = \"10.0.1.0/24\"",
  "  availability_zone       = \"ap-northeast-2c\"",
  "}[오전",
  "",
  "resource \"aws_lb_target_group\" \"lb_target_group\" {",
  "  vpc_id      = aws_vpc.vpc.id",
  "  target_type = \"instance\"",
  "  tags        = merge(var.tags, { Name = \"api-target-group\" })",
  "  region      = \"ap-northeast-2\"",
  "  protocol    = \"HTTP\"",
  "  port        = 8080",
  "  name        = \"sketchcatch-api-tg\"",
  "",
  "  health_check {",
  "    unhealthy_threshold = 3",
  "    path                = \"/health\"",
  "    matcher             = \"200-399\"",
  "    interval            = 30",
  "    healthy_threshold   = 2",
  "  }",
  "}",
  "",
  "resource \"aws_db_instance\" \"db_instance2\" {",
  "  username             = \"disabled\"",
  "  tags                 = merge(var.tags, { Name = \"disabled-rds-standby-placeholder\" })",
  "  skip_final_snapshot  = true",
  "  region               = \"ap-northeast-2\"",
  "  password             = random_password.db_password.result",
  "  instance_class       = \"db.t4g.micro\"",
  "  identifier           = \"disabled-rds-standby-placeholder\"",
  "  engine               = \"mysql\"",
  "  db_subnet_group_name = aws_db_subnet_group.db_snet_group.name",
  "  count                = 0",
  "  allocated_storage    = 20",
  "}",
  "",
  "resource \"aws_codepipeline\" \"codepipeline\" {",
  "  tags     = merge(var.tags, { Name = \"sketchcatch-pipeline\" })",
  "  role_arn = aws_iam_role.codepipeline_role.arn",
  "  region   = \"ap-northeast-2\"",
  "  name     = \"sketchcatch-pipeline\"",
  "",
  "  artifact_store {",
  "    type     = \"S3\"",
  "    location = aws_s3_bucket.s3_bucket2.bucket",
  "  }",
  "",
  "  stage {",
  "    name = \"Source\"",
  "",
  "    action {",
  "      version  = \"1\"",
  "      provider = \"CodeStarSourceConnection\"",
  "      owner    = \"AWS\"",
  "      name     = \"GitHubSource\"",
  "      category = \"Source\"",
  "",
  "      output_artifacts = [",
  "        \"source_output\",",
  "      ]",
  "",
  "      configuration = {",
  "        FullRepositoryId = \"${var.github_owner}/${var.github_repo}\"",
  "        ConnectionArn    = aws_codestarconnections_connection.github_connection.arn",
  "        BranchName       = var.github_branch",
  "      }",
  "    }",
  "  }",
  "",
  "  stage {",
  "    name = \"Build\"",
  "",
  "    action {",
  "      version  = \"1\"",
  "      provider = \"CodeBuild\"",
  "      owner    = \"AWS\"",
  "      name     = \"BuildAndPackage\"",
  "      category = \"Build\"",
  "",
  "      output_artifacts = [",
  "        \"build_output\",",
  "      ]",
  "",
  "      input_artifacts = [",
  "        \"source_output\",",
  "      ]",
  "",
  "      configuration = {",
  "        ProjectName = aws_codebuild_project.codebuild_project.name",
  "      }",
  "    }",
  "  }",
  "",
  "  stage {",
  "    name = \"Deploy\"",
  "",
  "    action {",
  "      version  = \"1\"",
  "      provider = \"CodeDeploy\"",
  "      owner    = \"AWS\"",
  "      name     = \"DeployToASG\"",
  "      category = \"Deploy\"",
  "",
  "      input_artifacts = [",
  "        \"build_output\",",
  "      ]",
  "",
  "      configuration = {",
  "        DeploymentGroupName = aws_codedeploy_deployment_group.codedeploy_deployment_group.deployment_group_name",
  "        ApplicationName     = aws_codedeploy_app.codedeploy_app.name",
  "      }",
  "    }",
  "  }",
  "}[오전",
  "",
  "resource \"aws_codebuild_project\" \"codebuild_project\" {",
  "  tags         = merge(var.tags, { Name = \"sketchcatch-build\" })",
  "  service_role = aws_iam_role.codebuild_role.arn",
  "  region       = \"ap-northeast-2\"",
  "  name         = \"sketchcatch-build\"",
  "",
  "  artifacts {",
  "    type = \"CODEPIPELINE\"",
  "  }",
  "",
  "  environment {",
  "    type            = \"LINUX_CONTAINER\"",
  "    privileged_mode = false",
  "    image           = \"aws/codebuild/amazonlinux-x86_64-standard:5.0\"",
  "    compute_type    = \"BUILD_GENERAL1_SMALL\"",
  "  }",
  "",
  "  logs_config {",
  "    cloudwatch_logs {",
  "      group_name = aws_cloudwatch_log_group.codebuild_logs.name",
  "    }",
  "  }",
  "",
  "  source {",
  "    type      = \"CODEPIPELINE\"",
  "    buildspec = <<-YAML",
  "      version: 0.2",
  "      phases:",
  "        install:",
  "          runtime-versions:",
  "            nodejs: 20",
  "        build:",
  "          commands:",
  "            - if [ -d apps/web ]; then cd apps/web && npm ci && npm run build && cd ../..; fi",
  "            - if [ -d apps/web/dist ]; then aws s3 sync apps/web/dist s3://${aws_s3_bucket.s3_bucket.bucket} --delete; fi",
  "            - if [ -d apps/web/build ]; then aws s3 sync apps/web/build s3://${aws_s3_bucket.s3_bucket.bucket} --delete; fi",
  "            - aws cloudfront create-invalidation --distribution-id ${aws_cloudfront_distribution.cloudfront_distribution.id} --paths \"/*\"",
  "            - mkdir -p deploy",
  "            - cp -r apps/api/* deploy/ 2>/dev/null || true",
  "            - cp appspec.yml deploy/ 2>/dev/null || true",
  "            - cp -r scripts deploy/scripts 2>/dev/null || true",
  "      artifacts:",
  "        base-directory: deploy",
  "        files:",
  "          - '**/*'",
  "    YAML",
  "  }",
  "}",
  "",
  "resource \"aws_codedeploy_app\" \"codedeploy_app\" {",
  "  tags             = merge(var.tags, { Name = \"sketchcatch-api-codedeploy-app\" })",
  "  region           = \"ap-northeast-2\"",
  "  name             = \"sketchcatch-api\"",
  "  compute_platform = \"Server\"",
  "}",
  "",
  "resource \"aws_codedeploy_deployment_group\" \"codedeploy_deployment_group\" {",
  "  tags                   = merge(var.tags, { Name = \"sketchcatch-api-deployment-group\" })",
  "  service_role_arn       = aws_iam_role.codedeploy_role.arn",
  "  region                 = \"ap-northeast-2\"",
  "  deployment_group_name  = \"sketchcatch-api-deployment-group\"",
  "  deployment_config_name = \"CodeDeployDefault.OneAtATime\"",
  "  app_name               = aws_codedeploy_app.codedeploy_app.name",
  "",
  "  autoscaling_groups = [",
  "    aws_autoscaling_group.autoscaling_group.name,",
  "  ]",
  "",
  "  auto_rollback_configuration {",
  "    enabled = true",
  "",
  "    events = [",
  "      \"DEPLOYMENT_FAILURE\",",
  "    ]",
  "  }",
  "",
  "  deployment_style {",
  "    deployment_type   = \"IN_PLACE\"",
  "    deployment_option = \"WITH_TRAFFIC_CONTROL\"",
  "  }",
  "",
  "  load_balancer_info {",
  "    target_group_info {",
  "      name = aws_lb_target_group.lb_target_group.name",
  "    }",
  "  }",
  "}",
  "",
  "resource \"aws_s3_bucket\" \"s3_bucket2\" {",
  "  tags          = merge(var.tags, { Name = \"artifact-s3-bucket\" })",
  "  region        = \"ap-northeast-2\"",
  "  force_destroy = true",
  "  bucket        = \"sketchcatch-artifact-${data.aws_caller_identity.current.account_id}\"",
  "}",
  "",
  "resource \"random_password\" \"db_password\" {",
  "  special = true",
  "  length  = 24",
  "}",
  "",
  "resource \"terraform_data\" \"terraform_resource\" {",
  "  input = \"placeholder\"",
  "}",
  "",
  "resource \"aws_route_table\" \"public_route_table\" {",
  "  vpc_id = aws_vpc.vpc.id",
  "  tags   = merge(var.tags, { Name = \"public-route-table\" })",
  "  region = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_route_table\" \"private_app_a_route_table\" {",
  "  vpc_id = aws_vpc.vpc.id",
  "  tags   = merge(var.tags, { Name = \"private-app-a-route-table\" })",
  "  region = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_route_table\" \"private_app_c_route_table\" {",
  "  vpc_id = aws_vpc.vpc.id",
  "  tags   = merge(var.tags, { Name = \"private-app-c-route-table\" })",
  "  region = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_route_table\" \"private_db_route_table\" {",
  "  vpc_id = aws_vpc.vpc.id",
  "  tags   = merge(var.tags, { Name = \"private-db-route-table\" })",
  "  region = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_route_table_association\" \"public_a\" {",
  "  subnet_id      = aws_subnet.snet4.id",
  "  route_table_id = aws_route_table.public_route_table.id",
  "  region         = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_route_table_association\" \"private_app_a\" {",
  "  subnet_id      = aws_subnet.snet2.id",
  "  route_table_id = aws_route_table.private_app_a_route_table.id",
  "  region         = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_route_table_association\" \"private_app_c\" {",
  "  subnet_id      = aws_subnet.snet3.id",
  "  route_table_id = aws_route_table.private_app_c_route_table.id",
  "  region         = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_route_table_association\" \"private_db_a\" {",
  "  subnet_id      = aws_subnet.snet7.id",
  "  route_table_id = aws_route_table.private_db_route_table.id",
  "  region         = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_route_table_association\" \"private_db_c\" {",
  "  subnet_id      = aws_subnet.snet6.id",
  "  route_table_id = aws_route_table.private_db_route_table.id",
  "  region         = \"ap-northeast-2\"",
  "}",
  "",
  "resource \"aws_eip\" \"nat_eip_a\" {",
  "  tags   = merge(var.tags, { Name = \"nat-eip-a\" })",
  "  region = \"ap-northeast-2\"",
  "  domain = \"vpc\"",
  "}",
  "",
  "resource \"aws_eip\" \"nat_eip_c\" {",
  "  tags   = merge(var.tags, { Name = \"nat-eip-c\" })",
  "  region = \"ap-northeast-2\"",
  "  domain = \"vpc\"",
  "}",
  "",
  "resource \"aws_nat_gateway\" \"nat_gateway_a\" {",
  "  tags          = merge(var.tags, { Name = \"nat-gateway-a\" })",
  "  subnet_id     = aws_subnet.snet4.id",
  "  region        = \"ap-northeast-2\"",
  "  allocation_id = aws_eip.nat_eip_a.id",
  "",
  "  depends_on = [",
  "    aws_internet_gateway.internet_gw,",
  "  ]",
  "}",
  "",
  "resource \"aws_nat_gateway\" \"nat_gateway_c\" {",
  "  tags          = merge(var.tags, { Name = \"nat-gateway-c\" })",
  "  subnet_id     = aws_subnet.snet5.id",
  "  region        = \"ap-northeast-2\"",
  "  allocation_id = aws_eip.nat_eip_c.id",
  "",
  "  depends_on = [",
  "    aws_internet_gateway.internet_gw,",
  "  ]",
  "}",
  "",
  "resource \"aws_security_group_rule\" \"alb_egress\" {",
  "  type                     = \"egress\"",
  "  to_port                  = 8080",
  "  source_security_group_id = aws_security_group.sg6.id",
  "  security_group_id        = aws_security_group.sg.id",
  "  region                   = \"ap-northeast-2\"",
  "  protocol                 = \"tcp\"",
  "  from_port                = 8080",
  "}",
  "",
  "resource \"aws_security_group_rule\" \"app_egress\" {",
  "  type              = \"egress\"",
  "  to_port           = 0",
  "  security_group_id = aws_security_group.sg6.id",
  "  region            = \"ap-northeast-2\"",
  "  protocol          = \"-1\"",
  "  from_port         = 0",
  "",
  "  cidr_blocks = [",
  "    \"0.0.0.0/0\",",
  "  ]",
  "}",
  "",
  "resource \"aws_lb_listener\" \"http_listener\" {",
  "  region            = \"ap-northeast-2\"",
  "  protocol          = \"HTTP\"",
  "  port              = 80",
  "  load_balancer_arn = aws_lb.lb.arn",
  "",
  "  default_action {",
  "    type             = \"forward\"",
  "    target_group_arn = aws_lb_target_group.lb_target_group.arn",
  "  }",
  "}",
  "",
  "resource \"aws_cloudfront_origin_access_control\" \"s3_oac\" {",
  "  signing_protocol                  = \"sigv4\"",
  "  signing_behavior                  = \"always\"",
  "  origin_access_control_origin_type = \"s3\"",
  "  name                              = \"sketchcatch-static-oac\"",
  "  description                       = \"OAC for static frontend S3 bucket\"",
  "}",
  "",
  "resource \"aws_s3_bucket_public_access_block\" \"static_frontend_public_access_block\" {",
  "  restrict_public_buckets = true",
  "  region                  = \"ap-northeast-2\"",
  "  ignore_public_acls      = true",
  "  bucket                  = aws_s3_bucket.s3_bucket.id",
  "  block_public_policy     = true",
  "  block_public_acls       = true",
  "}",
  "",
  "resource \"aws_s3_bucket_policy\" \"static_frontend_bucket_policy\" {",
  "  region = \"ap-northeast-2\"",
  "  policy = jsonencode({",
  "    Version = \"2012-10-17\"",
  "    Statement = [{",
  "      Effect = \"Allow\"",
  "      Principal = {",
  "        Service = \"cloudfront.amazonaws.com\"",
  "      }",
  "      Action   = \"s3:GetObject\"",
  "      Resource = \"${aws_s3_bucket.s3_bucket.arn}/*\"",
  "      Condition = {",
  "        StringEquals = {",
  "          \"AWS:SourceArn\" = aws_cloudfront_distribution.cloudfront_distribution.arn",
  "        }",
  "      }",
  "    }]",
  "  })",
  "  bucket = aws_s3_bucket.s3_bucket.id",
  "}",
  "",
  "resource \"aws_iam_role\" \"ec2_role\" {",
  "  name = \"sketchcatch-ec2-role\"",
  "  assume_role_policy = jsonencode({",
  "    Version = \"2012-10-17\"",
  "    Statement = [{",
  "      Effect = \"Allow\"",
  "      Principal = {",
  "        Service = \"ec2.amazonaws.com\"",
  "      }",
  "      Action = \"sts:AssumeRole\"",
  "    }]",
  "  })",
  "}[오전",
  "",
  "resource \"aws_iam_instance_profile\" \"ec2_instance_profile\" {",
  "  role = aws_iam_role.ec2_role.name",
  "  name = \"sketchcatch-ec2-instance-profile\"",
  "}",
  "",
  "resource \"aws_iam_role_policy\" \"ec2_policy\" {",
  "  role = aws_iam_role.ec2_role.id",
  "  policy = jsonencode({",
  "    Version = \"2012-10-17\"",
  "    Statement = [{",
  "      Effect = \"Allow\"",
  "      Action = [\"s3:GetObject\", \"s3:ListBucket\"]",
  "      Resource = [",
  "        aws_s3_bucket.s3_bucket2.arn,",
  "        \"${aws_s3_bucket.s3_bucket2.arn}/*\"",
  "      ]",
  "      }, {",
  "      Effect = \"Allow\"",
  "      Action = [",
  "        \"secretsmanager:GetSecretValue\",",
  "        \"logs:CreateLogGroup\",",
  "        \"logs:CreateLogStream\",",
  "        \"logs:PutLogEvents\",",
  "        \"cloudwatch:PutMetricData\"",
  "      ]",
  "      Resource = \"*\"",
  "    }]",
  "  })",
  "  name = \"sketchcatch-ec2-policy\"",
  "}",
  "",
  "resource \"aws_iam_role_policy_attachment\" \"ec2_ssm\" {",
  "  role       = aws_iam_role.ec2_role.name",
  "  policy_arn = \"arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore\"",
  "}",
  "",
  "resource \"aws_iam_role_policy_attachment\" \"ec2_codedeploy\" {",
  "  role       = aws_iam_role.ec2_role.name",
  "  policy_arn = \"arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy\"",
  "}",
  "",
  "resource \"aws_launch_template\" \"launch_template\" {",
  "  user_data = base64encode(<<-EOF",
  "    #!/bin/bash",
  "    dnf update -y",
  "    dnf install -y ruby wget",
  "    cd /home/ec2-user",
  "    wget https://aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com/latest/install",
  "    chmod +x ./install",
  "    ./install auto",
  "    systemctl enable codedeploy-agent",
  "    systemctl start codedeploy-agent",
  "  EOF",
  "  )",
  "  tags          = merge(var.tags, { Name = \"sketchcatch-api-launch-template\" })",
  "  region        = \"ap-northeast-2\"",
  "  name_prefix   = \"sketchcatch-api-\"",
  "  instance_type = \"t3.micro\"",
  "  image_id      = data.aws_ssm_parameter.al2023_ami.value",
  "",
  "  vpc_security_group_ids = [",
  "    aws_security_group.sg6.id,",
  "  ]",
  "",
  "  iam_instance_profile {",
  "    name = aws_iam_instance_profile.ec2_instance_profile.name",
  "  }",
  "}",
  "",
  "resource \"aws_codestarconnections_connection\" \"github_connection\" {",
  "  region        = \"ap-northeast-2\"",
  "  provider_type = \"GitHub\"",
  "  name          = \"sketchcatch-github-connection\"",
  "}",
  "",
  "resource \"aws_iam_role\" \"codebuild_role\" {",
  "  name = \"sketchcatch-codebuild-role\"",
  "  assume_role_policy = jsonencode({",
  "    Version = \"2012-10-17\"",
  "    Statement = [{",
  "      Effect = \"Allow\"",
  "      Principal = {",
  "        Service = \"codebuild.amazonaws.com\"",
  "      }",
  "      Action = \"sts:AssumeRole\"",
  "    }]",
  "  })",
  "}",
  "",
  "resource \"aws_iam_role_policy\" \"codebuild_policy\" {",
  "  role = aws_iam_role.codebuild_role.id",
  "  policy = jsonencode({",
  "    Version = \"2012-10-17\"",
  "    Statement = [{",
  "      Effect = \"Allow\"",
  "      Action = [",
  "        \"logs:*\",",
  "        \"s3:*\",",
  "        \"cloudfront:CreateInvalidation\"",
  "      ]",
  "      Resource = \"*\"",
  "    }]",
  "  })",
  "  name = \"sketchcatch-codebuild-policy\"",
  "}",
  "",
  "resource \"aws_cloudwatch_log_group\" \"codebuild_logs\" {",
  "  retention_in_days = 14",
  "  region            = \"ap-northeast-2\"",
  "  name              = \"/aws/codebuild/sketchcatch\"",
  "}",
  "",
  "resource \"aws_iam_role\" \"codedeploy_role\" {",
  "  name = \"sketchcatch-codedeploy-role\"",
  "  assume_role_policy = jsonencode({",
  "    Version = \"2012-10-17\"",
  "    Statement = [{",
  "      Effect = \"Allow\"",
  "      Principal = {",
  "        Service = \"codedeploy.amazonaws.com\"",
  "      }",
  "      Action = \"sts:AssumeRole\"",
  "    }]",
  "  })",
  "}",
  "",
  "resource \"aws_iam_role_policy_attachment\" \"codedeploy_role_policy\" {",
  "  role       = aws_iam_role.codedeploy_role.name",
  "  policy_arn = \"arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole\"",
  "}",
  "",
  "resource \"aws_iam_role\" \"codepipeline_role\" {",
  "  name = \"sketchcatch-codepipeline-role\"",
  "  assume_role_policy = jsonencode({",
  "    Version = \"2012-10-17\"",
  "    Statement = [{",
  "      Effect = \"Allow\"",
  "      Principal = {",
  "        Service = \"codepipeline.amazonaws.com\"",
  "      }",
  "      Action = \"sts:AssumeRole\"",
  "    }]",
  "  })",
  "}",
  "",
  "resource \"aws_iam_role_policy\" \"codepipeline_policy\" {",
  "  role = aws_iam_role.codepipeline_role.id",
  "  policy = jsonencode({",
  "    Version = \"2012-10-17\"",
  "    Statement = [{",
  "      Effect = \"Allow\"",
  "      Action = [",
  "        \"s3:*\",",
  "        \"codebuild:*\",",
  "        \"codedeploy:*\",",
  "        \"codeconnections:UseConnection\",",
  "        \"codestar-connections:UseConnection\"",
  "      ]",
  "      Resource = \"*\"",
  "    }]",
  "  })",
  "  name = \"sketchcatch-codepipeline-policy\"",
  "}",
  "",
  "resource \"aws_secretsmanager_secret\" \"db_credentials\" {",
  "  tags   = merge(var.tags, { Name = \"db-credentials\" })",
  "  region = \"ap-northeast-2\"",
  "  name   = \"sketchcatch/db\"",
  "}[오전",
  "",
  "resource \"aws_secretsmanager_secret_version\" \"db_credentials_version\" {",
  "  secret_string = jsonencode({",
  "    host     = aws_db_instance.db_instance.address",
  "    port     = 3306",
  "    dbname   = aws_db_instance.db_instance.db_name",
  "    username = aws_db_instance.db_instance.username",
  "    password = random_password.db_password.result",
  "  })",
  "  secret_id = aws_secretsmanager_secret.db_credentials.id",
  "  region    = \"ap-northeast-2\"",
  "}",
  "",
  "data \"aws_caller_identity\" \"current\" {",
  "}",
  "",
  "data \"aws_ssm_parameter\" \"al2023_ami\" {",
  "  name = \"/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64\"",
  "}",
  "",
  "resource \"aws_route\" \"public_default_route\" {",
  "  route_table_id         = aws_route_table.public_route_table.id",
  "  region                 = \"ap-northeast-2\"",
  "  gateway_id             = aws_internet_gateway.internet_gw.id",
  "  destination_cidr_block = \"0.0.0.0/0\"",
  "}",
  "",
  "resource \"aws_route\" \"private_app_a_default_route\" {",
  "  route_table_id         = aws_route_table.private_app_a_route_table.id",
  "  region                 = \"ap-northeast-2\"",
  "  nat_gateway_id         = aws_nat_gateway.nat_gateway_a.id",
  "  destination_cidr_block = \"0.0.0.0/0\"",
  "}",
  "",
  "resource \"aws_route\" \"private_app_c_default_route\" {",
  "  route_table_id         = aws_route_table.private_app_c_route_table.id",
  "  region                 = \"ap-northeast-2\"",
  "  nat_gateway_id         = aws_nat_gateway.nat_gateway_c.id",
  "  destination_cidr_block = \"0.0.0.0/0\"",
  "}",
  "",
  "resource \"aws_route_table_association\" \"public_b\" {",
  "  subnet_id      = aws_subnet.snet5.id",
  "  route_table_id = aws_route_table.public_route_table.id",
  "  region         = \"ap-northeast-2\"",
  "}",
  "",
].join("\n");
