import type { ResourceType } from "@sketchcatch/types";

export const RESOURCE_TYPE_KOREAN_NAMES = {
  VPC: "가상 사설 클라우드",
  SUBNET: "서브넷",
  INTERNET_GATEWAY: "인터넷 게이트웨이",
  ROUTE_TABLE: "라우트 테이블",
  ROUTE_TABLE_ASSOCIATION: "라우트 테이블 연결",
  NETWORK_ACL: "네트워크 ACL",
  NETWORK_ACL_RULE: "네트워크 ACL 규칙",
  VPC_PEERING_CONNECTION: "VPC 피어링 연결",
  NAT_GATEWAY: "NAT 게이트웨이",
  EC2: "EC2 인스턴스",
  AUTO_SCALING_GROUP: "오토 스케일링 그룹",
  AUTO_SCALING_POLICY: "오토 스케일링 정책",
  LAUNCH_TEMPLATE: "시작 템플릿",
  KEY_PAIR: "키 페어",
  ELASTIC_IP: "탄력적 IP",
  EBS_VOLUME: "EBS 볼륨",
  VOLUME_ATTACHMENT: "EBS 볼륨 연결",
  EFS_FILE_SYSTEM: "EFS 파일 시스템",
  EFS_MOUNT_TARGET: "EFS 마운트 대상",
  EFS_ACCESS_POINT: "EFS 액세스 포인트",
  RDS: "RDS 데이터베이스",
  RDS_READ_REPLICA: "RDS 읽기 복제본",
  RDS_CLUSTER: "RDS 클러스터",
  RDS_CLUSTER_INSTANCE: "RDS 클러스터 인스턴스",
  S3: "S3 버킷",
  DYNAMODB_TABLE: "DynamoDB 테이블",
  ELASTICACHE_REDIS: "ElastiCache Redis",
  ELASTICACHE_SUBNET_GROUP: "ElastiCache 서브넷 그룹",
  ELASTICACHE_PARAMETER_GROUP: "ElastiCache 파라미터 그룹",
  SECURITY_GROUP: "보안 그룹",
  CLOUDFRONT: "CloudFront CDN",
  LOAD_BALANCER_TARGET_GROUP: "로드 밸런서 대상 그룹",
  LOAD_BALANCER_TARGET_GROUP_ATTACHMENT: "로드 밸런서 대상 그룹 연결",
  ROUTE53_RECORD: "Route 53 레코드",
  ROUTE53_ZONE: "Route 53 호스팅 영역",
  WAF_WEB_ACL: "WAF 웹 ACL",
  WAF_WEB_ACL_ASSOCIATION: "WAF 웹 ACL 연결",
  LOAD_BALANCER: "로드 밸런서",
  LOAD_BALANCER_LISTENER: "로드 밸런서 리스너",
  LAMBDA: "Lambda 함수",
  LAMBDA_ALIAS: "Lambda 별칭",
  LAMBDA_EVENT_SOURCE_MAPPING: "Lambda 이벤트 소스 매핑",
  AMI: "AMI 머신 이미지",
  IAM_ROLE: "IAM 역할",
  IAM_POLICY: "IAM 정책",
  IAM_INSTANCE_PROFILE: "IAM 인스턴스 프로파일",
  KMS_KEY: "KMS 암호화 키",
  KMS_ALIAS: "KMS 키 별칭",
  ACM_CERTIFICATE: "ACM 인증서",
  ACM_CERTIFICATE_VALIDATION: "ACM 인증서 검증",
  COGNITO_USER_POOL: "Cognito 사용자 풀",
  COGNITO_USER_POOL_CLIENT: "Cognito 사용자 풀 클라이언트",
  AMPLIFY_APP: "Amplify 앱",
  DB_SUBNET_GROUP: "DB 서브넷 그룹",
  SECRETS_MANAGER_SECRET: "Secrets Manager 보안 암호",
  RANDOM_PASSWORD: "Terraform 생성 보안 값",
  VPC_ENDPOINT: "VPC 엔드포인트",
  CLOUDWATCH_LOG_GROUP: "CloudWatch 로그 그룹",
  CLOUDWATCH_LOG_STREAM: "CloudWatch 로그 스트림",
  CLOUDWATCH_METRIC_ALARM: "CloudWatch 지표 경보",
  CLOUDWATCH_DASHBOARD: "CloudWatch 대시보드",
  CLOUDWATCH_LOG_RESOURCE_POLICY: "CloudWatch 로그 리소스 정책",
  CLOUDTRAIL: "CloudTrail 추적",
  XRAY_GROUP: "X-Ray 그룹",
  XRAY_SAMPLING_RULE: "X-Ray 샘플링 규칙",
  AWS_CALLER_IDENTITY: "AWS 호출자 자격 증명",
  SSM_PARAMETER: "SSM 파라미터",
  API_GATEWAY_REST_API: "API Gateway REST API",
  API_GATEWAY_AUTHORIZER: "API Gateway 권한 부여자",
  API_GATEWAY_WEBSOCKET_API: "API Gateway WebSocket API",
  API_GATEWAY_RESOURCE: "API Gateway 리소스",
  API_GATEWAY_METHOD: "API Gateway 메서드",
  API_GATEWAY_INTEGRATION: "API Gateway 통합",
  API_GATEWAY_DEPLOYMENT: "API Gateway 배포",
  API_GATEWAY_STAGE: "API Gateway 스테이지",
  API_GATEWAY_V2_ROUTE: "API Gateway V2 라우트",
  API_GATEWAY_V2_INTEGRATION: "API Gateway V2 통합",
  API_GATEWAY_V2_STAGE: "API Gateway V2 스테이지",
  LAMBDA_PERMISSION: "Lambda 호출 권한",
  SNS_TOPIC: "SNS 토픽",
  SNS_TOPIC_SUBSCRIPTION: "SNS 토픽 구독",
  SQS_QUEUE: "SQS 큐",
  EVENTBRIDGE_RULE: "EventBridge 규칙",
  EVENTBRIDGE_TARGET: "EventBridge 대상",
  EVENTBRIDGE_PERMISSION: "EventBridge 권한",
  SCHEDULER_SCHEDULE: "EventBridge Scheduler 일정",
  STEP_FUNCTIONS_STATE_MACHINE: "Step Functions 상태 머신",
  CODEBUILD_PROJECT: "CodeBuild 프로젝트",
  CODEDEPLOY_APP: "CodeDeploy 애플리케이션",
  CODEDEPLOY_DEPLOYMENT_GROUP: "CodeDeploy 배포 그룹",
  CODEPIPELINE: "CodePipeline 파이프라인",
  CODESTAR_CONNECTION: "CodeStar 연결",
  ECR_REPOSITORY: "ECR 저장소",
  ECR_LIFECYCLE_POLICY: "ECR 수명 주기 정책",
  ECS_CLUSTER: "ECS 클러스터",
  ECS_SERVICE: "ECS 서비스",
  APPLICATION_AUTO_SCALING_TARGET: "Application Auto Scaling 대상",
  APPLICATION_AUTO_SCALING_POLICY: "Application Auto Scaling 정책",
  ECS_TASK_DEFINITION: "ECS 태스크 정의",
  ECS_CAPACITY_PROVIDER: "ECS 용량 공급자",
  EKS_CLUSTER: "EKS 클러스터",
  EKS_NODE_GROUP: "EKS 노드 그룹",
  EKS_FARGATE_PROFILE: "EKS Fargate 프로파일",
  EKS_ADDON: "EKS 애드온",
  KUBERNETES_NAMESPACE: "쿠버네티스 네임스페이스",
  KUBERNETES_DEPLOYMENT: "쿠버네티스 디플로이먼트",
  KUBERNETES_SERVICE: "쿠버네티스 서비스",
  CONFIG_CONFIGURATION_RECORDER: "AWS Config 구성 기록기",
  CONFIG_DELIVERY_CHANNEL: "AWS Config 전송 채널",
  CONFIG_RULE: "AWS Config 규칙",
  SHIELD_PROTECTION: "AWS Shield 보호",
  GUARDDUTY_DETECTOR: "GuardDuty 탐지기"
} satisfies Record<Exclude<ResourceType, "UNKNOWN">, string>;

const COMMON_RESOURCE_ALIASES: Partial<Record<Exclude<ResourceType, "UNKNOWN">, readonly string[]>> = {
  VPC: ["VPC", "브이피씨", "가상 네트워크", "사설 네트워크"],
  SUBNET: ["서브 네트워크", "서브 네트워크 영역"],
  INTERNET_GATEWAY: ["IGW", "인터넷 GW", "외부 인터넷 게이트웨이"],
  NAT_GATEWAY: ["NAT GW", "내트 게이트웨이", "아웃바운드 게이트웨이"],
  EC2: ["EC2", "서버", "가상 서버", "컴퓨트 인스턴스"],
  AUTO_SCALING_GROUP: ["ASG", "자동 확장 그룹", "서버 자동 확장"],
  ELASTIC_IP: ["EIP", "고정 공인 IP", "탄력 IP"],
  RDS: ["DB", "데이터베이스", "관계형 데이터베이스", "데이터 저장소"],
  RDS_READ_REPLICA: ["읽기 전용 DB", "DB 읽기 복제본", "리드 레플리카"],
  S3: ["오브젝트 스토리지", "파일 저장소", "스토리지 버킷", "버킷"],
  DYNAMODB_TABLE: ["DynamoDB", "다이나모디비", "NoSQL 테이블"],
  ELASTICACHE_REDIS: ["Redis 캐시", "레디스", "인메모리 캐시"],
  SECURITY_GROUP: ["방화벽", "보안 설정", "SG", "접근 제어 그룹"],
  CLOUDFRONT: ["CDN", "클라우드프론트", "콘텐츠 전송 네트워크"],
  LOAD_BALANCER: ["ALB", "ELB", "로드밸런서", "부하 분산기", "트래픽 분산기"],
  LOAD_BALANCER_TARGET_GROUP: ["ALB 대상 그룹", "타깃 그룹", "타겟 그룹"],
  LOAD_BALANCER_LISTENER: ["ALB 리스너", "트래픽 수신 규칙"],
  ROUTE53_RECORD: ["DNS 레코드", "도메인 레코드", "라우트53 레코드"],
  ROUTE53_ZONE: ["DNS 호스팅 영역", "호스티드 존", "도메인 영역"],
  WAF_WEB_ACL: ["웹 방화벽", "WAF", "웹 ACL"],
  LAMBDA: ["람다", "서버리스 함수", "클라우드 함수"],
  AMI: ["머신 이미지", "서버 이미지", "EC2 이미지"],
  IAM_ROLE: ["IAM 롤", "접근 역할", "권한 역할"],
  IAM_POLICY: ["권한 정책", "접근 정책", "IAM 폴리시"],
  KMS_KEY: ["암호화 키", "고객 관리 키", "CMK"],
  ACM_CERTIFICATE: ["SSL 인증서", "TLS 인증서", "HTTPS 인증서"],
  COGNITO_USER_POOL: ["회원 인증 풀", "사용자 인증 저장소", "유저 풀"],
  SECRETS_MANAGER_SECRET: ["시크릿", "비밀 값", "비밀 저장소", "자격 증명 보관소"],
  VPC_ENDPOINT: ["프라이빗 엔드포인트", "서비스 엔드포인트"],
  CLOUDWATCH_LOG_GROUP: ["로그 그룹", "애플리케이션 로그 저장소"],
  CLOUDWATCH_METRIC_ALARM: ["모니터링 알람", "지표 알람", "CloudWatch 알람"],
  CLOUDWATCH_DASHBOARD: ["모니터링 대시보드", "운영 대시보드"],
  CLOUDTRAIL: ["감사 로그", "API 활동 추적", "클라우드트레일"],
  SSM_PARAMETER: ["파라미터 스토어", "설정 값 저장소", "SSM 설정"],
  API_GATEWAY_REST_API: ["API Gateway", "API 게이트웨이", "REST API 입구", "API 입구"],
  API_GATEWAY_WEBSOCKET_API: ["웹소켓 API", "실시간 API 게이트웨이"],
  SNS_TOPIC: ["메시지 토픽", "알림 토픽", "게시 구독 토픽"],
  SQS_QUEUE: ["메시지 큐", "작업 큐", "비동기 큐"],
  EVENTBRIDGE_RULE: ["이벤트 규칙", "이벤트브리지 룰"],
  SCHEDULER_SCHEDULE: ["예약 실행 일정", "스케줄러", "정기 실행 일정"],
  STEP_FUNCTIONS_STATE_MACHINE: ["워크플로 상태 머신", "스텝 펑션", "서버리스 워크플로"],
  CODEBUILD_PROJECT: ["빌드 프로젝트", "CI 빌드"],
  CODEDEPLOY_APP: ["배포 애플리케이션", "코드디플로이 앱"],
  CODEPIPELINE: ["CI/CD 파이프라인", "배포 파이프라인", "코드파이프라인"],
  ECR_REPOSITORY: ["컨테이너 이미지 저장소", "도커 이미지 저장소", "ECR 리포지토리"],
  ECS_CLUSTER: ["컨테이너 클러스터", "ECS 실행 클러스터"],
  ECS_SERVICE: ["컨테이너 서비스", "Fargate 서비스", "ECS 앱 서비스"],
  ECS_TASK_DEFINITION: ["컨테이너 태스크 정의", "Fargate 태스크 정의"],
  EKS_CLUSTER: ["쿠버네티스 클러스터", "관리형 쿠버네티스"],
  EKS_NODE_GROUP: ["쿠버네티스 노드 그룹", "워커 노드 그룹"],
  KUBERNETES_DEPLOYMENT: ["K8s 디플로이먼트", "쿠버네티스 배포"],
  KUBERNETES_SERVICE: ["K8s 서비스", "쿠버네티스 서비스 오브젝트"],
  SHIELD_PROTECTION: ["디도스 보호", "DDoS 방어", "Shield 보호"],
  GUARDDUTY_DETECTOR: ["위협 탐지기", "보안 위협 탐지", "가드듀티"]
};

export function getNaturalLanguageResourceAliases(
  resourceType: Exclude<ResourceType, "UNKNOWN">
): string[] {
  const koreanName = RESOURCE_TYPE_KOREAN_NAMES[resourceType];
  const providerPrefix =
    koreanName.startsWith("AWS ") || koreanName.startsWith("쿠버네티스 ")
      ? []
      : [`AWS ${koreanName}`];

  return Array.from(
    new Set([
      koreanName,
      koreanName.replaceAll(" ", ""),
      `${koreanName} 리소스`,
      ...providerPrefix,
      ...(COMMON_RESOURCE_ALIASES[resourceType] ?? [])
    ])
  );
}
