/** Resource definitions exposed in the manual Palette by the reference templates. */
export const referenceTemplatePaletteResourceIds = [
  "aws-api-gateway-integration-response",
  "aws-api-gateway-method-response",
  "aws-budgets-budget",
  "aws-cloudfront-origin-access-identity",
  "aws-docdb-cluster",
  "aws-dynamodb-global-table",
  "aws-elastic-beanstalk-application",
  "aws-elastic-beanstalk-environment",
  "aws-elb",
  "aws-flow-log",
  "aws-fsx-lustre-file-system",
  "aws-iam-group",
  "aws-iam-group-policy-attachment",
  "aws-iam-user",
  "aws-iam-user-group-membership",
  "aws-iam-user-login-profile",
  "aws-launch-configuration",
  "aws-main-route-table-association",
  "aws-network-interface",
  "aws-organizations-account",
  "aws-s3-bucket-acl",
  "aws-s3-bucket-logging",
  "aws-s3-bucket-notification",
  "aws-s3-bucket-object",
  "aws-s3-bucket-replication-configuration",
  "aws-ses-email-identity",
  "aws-vpc-peering-connection-accepter",
  "aws-waf-ipset",
  "aws-waf-rule",
  "aws-waf-web-acl",
  "aws-iam-policy-data"
] as const;
